#!/usr/bin/env python3
"""Batch 2: Step 1 remaining (Immunology + Genetics + Neurology + Internal Med = 55) + Step 2 (250)"""
import sys

# Questions accumulated as TS array elements
lines = []
START_ID = 929 + 80  # after batch 1 (80 qs)
next_id = START_ID

def q(id_num, step, subject, question_text, options, correct, en, zh, es, diff="Medium", hy_tag=None):
    qt = question_text.replace("'", "\\'")
    opts = ", ".join(f"'{o.replace(chr(39), chr(92)+chr(39))}'" for o in options)
    en2 = en.replace("'", "\\'")
    zh2 = zh.replace("'", "\\'")
    es2 = es.replace("'", "\\'")
    l = f"  {{\n    id: {id_num}, step: '{step}', subject: '{subject}',\n    question: '{qt}',\n    options: [{opts}],\n    correctAnswer: {correct},\n    explanationEn: '{en2}',\n    explanationZh: '{zh2}',\n    explanationEs: '{es2}',\n    aiGenerated: true,\n    difficulty: '{diff}'"
    if hy_tag:
        l += f",\n    highYieldTag: '{hy_tag}'"
    l += "\n  },"
    lines.append(l)

# --- Immunology (15 questions) ---
immuno_qs = [
    ("Which immunoglobulin is the first to be produced in a primary immune response?",
     ["IgM", "IgG", "IgA", "IgE", "IgD"], 0,
     "IgM is produced first in primary immune response (pentamer, fixes complement well). IgG is produced later in primary and dominates secondary response. IgM presence suggests acute/recent infection. IgG presence suggests past infection or vaccination.",
     "IgM在初次免疫应答中最先产生。IgG后来产生并主导再次应答。IgM存在提示急性/近期感染。IgG存在提示既往感染或疫苗接种。",
     "IgM: primera en respuesta primaria (pentamero, fija complemento). IgG: tardia en primaria, domina secundaria."),
    ("Which hypersensitivity type is involved in allergic asthma (Type I)?",
     ["Type I — IgE-mediated mast cell degranulation", "Type II — antibody-mediated cytotoxicity", "Type III — immune complex deposition", "Type IV — T-cell mediated (delayed)", "Mixed Type II and III"], 0,
     "Type I hypersensitivity: IgE bound to mast cells/basophils → antigen cross-linking → degranulation (histamine, leukotrienes, prostaglandins). Examples: allergic asthma, anaphylaxis, allergic rhinitis, food allergies.",
     "I型超敏反应：IgE结合于肥大细胞/嗜碱性粒细胞→抗原交联→脱颗粒。例如：过敏性哮喘、过敏性鼻炎、食物过敏。",
     "Hipersensibilidad tipo I: IgE en mastocitos → desgranulacion. Ejemplos: asma alergica, anafilaxia, rinitis alergica."),
    ("Which CD4+ T cell subset is involved in defense against intracellular pathogens like Mycobacterium tuberculosis?",
     ["Th1 cells (secrete IFN-gamma)", "Th2 cells (secrete IL-4, IL-5)", "Th17 cells (secrete IL-17)", "Treg cells (secrete IL-10, TGF-beta)", "Tfh cells (help B cells in germinal centers)"], 0,
     "Th1: IFN-gamma → activates macrophages (intracellular pathogens). Th2: IL-4, IL-5, IL-13 → parasites, allergies. Th17: extracellular bacteria, fungi. Treg: immune suppression. Tfh: B cell help in germinal centers.",
     "Th1：IFN-γ→激活巨噬细胞（胞内病原体）。Th2：寄生虫、过敏。Th17：胞外细菌、真菌。Treg：免疫抑制。Tfh：生发中心B细胞辅助。",
     "Th1: IFN-gamma → activa macrofagos. Th2: IL-4/5/13 → parasitos, alergias. Th17: bacterias extracelulares. Treg: supresion."),
    ("Which complement pathway is activated by antibody-antigen complexes?",
     ["Classical pathway (C1q binds Fc region of IgG/IgM)", "Alternative pathway", "Lectin pathway", "Terminal pathway only", "All pathways simultaneously"], 0,
     "Classical: C1q binds Fc of IgG/IgM immune complexes. Alternative: spontaneous C3 hydrolysis, properdin stabilizes. Lectin: mannose-binding lectin binds pathogen carbohydrates. All three converge at C3 convertase.",
     "经典途径：C1q结合IgG/IgM免疫复合物Fc段。替代途径：C3自发水解。凝集素途径：MBL结合病原体糖类。三者在C3转化酶处汇合。",
     "Via clasica: C1q une Fc de IgG/IgM. Alternativa: hidrolisis espontanea C3. Lectina: MBL une carbohidratos. Convergen en C3 convertasa."),
    ("A 5M child with recurrent pyogenic infections (Staphylococcus, Streptococcus) and eczema. Lab shows elevated IgE and low platelet count. What syndrome?",
     ["Wiskott-Aldrich syndrome (WAS)", "DiGeorge syndrome", "Bruton agammaglobulinemia", "Chronic granulomatous disease", "Hyper-IgM syndrome"], 0,
     "WAS: X-linked, triad of thrombocytopenia + eczema + recurrent infections. WASp protein mutation → defective cytoskeleton in hematopoietic cells. Lab: low platelets (small), elevated IgE, low IgM. Treatment: HSCT.",
     "WAS：X连锁，三联征：血小板减少+湿疹+反复感染。WASp蛋白突变。实验室：血小板减少（小血小板）、IgE升高、IgM降低。治疗：HSCT。",
     "WAS: ligado X, triada: trombocitopenia + eczema + infecciones recurrentes. Mutacion proteina WASp. IgE elevada, IgM baja."),
    ("Which medication class is a calcineurin inhibitor used for transplant immunosuppression?",
     ["Tacrolimus (and cyclosporine)", "Mycophenolate mofetil", "Sirolimus", "Azathioprine", "Belatacept"], 0,
     "Tacrolimus and cyclosporine inhibit calcineurin → decreased IL-2 transcription → decreased T cell activation. Tacrolimus is more potent than cyclosporine. Nephrotoxicity, neurotoxicity, hypertension, hyperglycemia. Monitor drug levels.",
     "他克莫司和环孢素抑制钙调磷酸酶→减少IL-2转录→减少T细胞活化。他克莫司比环孢素更强效。肾毒性、神经毒性、高血压、高血糖。监测血药浓度。",
     "Tacrolimus y ciclosporina inhiben calcineurina → menos IL-2 → menos activacion T. Tacrolimus mas potente. Nefrotoxicidad, HTA, hiperglucemia."),
    ("Which type of transplant rejection occurs within minutes to hours and is mediated by preformed antibodies?",
     ["Hyperacute rejection", "Acute cellular rejection", "Acute antibody-mediated rejection", "Chronic rejection", "Graft-versus-host disease"], 0,
     "Hyperacute: preformed anti-donor antibodies (ABO or anti-HLA) → minutes to hours → widespread thrombosis. Prevented by cross-matching. Acute: days to months (T cells or antibodies). Chronic: months to years (fibrosis, vascular changes).",
     "超急性排斥：预存抗供体抗体→数分钟至数小时→广泛血栓形成。通过交叉配型预防。急性：数天至数月。慢性：数月至数年（纤维化、血管病变）。",
     "Rechazo hiperagudo: anticuerpos preformados anti-donante → minutos a horas → trombosis masiva. Prevenido por prueba cruzada."),
    ("Which primary immunodeficiency involves defective NADPH oxidase and leads to recurrent catalase-positive infections?",
     ["Chronic granulomatous disease (CGD)", "Leukocyte adhesion deficiency", "Chediak-Higashi syndrome", "Myeloperoxidase deficiency", "Severe combined immunodeficiency (SCID)"], 0,
     "CGD: defective NADPH oxidase → cannot produce ROS for intracellular killing → recurrent infections with catalase-positive organisms (S. aureus, Serratia, Burkholderia, Aspergillus). Nitroblue tetrazolium (NBT) test negative. Dihydrorhodamine flow cytometry confirms.",
     "CGD：NADPH氧化酶缺陷→不能产生ROS→反复过氧化氢酶阳性菌感染。NBT试验阴性。二氢罗丹明流式细胞术确诊。",
     "EGC: defecto NADPH oxidasa → no produce ROS → infecciones catalasa-positivas. Prueba NBT negativa. Citometria dihidrorodamina confirma."),
    ("Which autoantibody is most specific for systemic lupus erythematosus (SLE)?",
     ["Anti-dsDNA", "ANA (antinuclear antibody)", "Anti-Ro (SSA)", "Anti-Smith (Sm)", "Anti-U1 RNP"], 0,
     "Anti-dsDNA: highly specific for SLE, correlates with disease activity (especially nephritis). Anti-Smith (Sm) is very specific but not sensitive. ANA is sensitive but not specific. Anti-Ro associated with neonatal lupus and photosensitivity.",
     "抗dsDNA：对SLE高度特异，与疾病活动度相关（特别是肾炎）。抗Sm非常特异但灵敏度不高。ANA敏感但不特异。",
     "Anti-ADNdc: altamente especifico LES, correlaciona actividad (nefritis). Anti-Sm: muy especifico, poca sensibilidad. ANA sensible, no especifico."),
    ("What is the mechanism of action of omalizumab?",
     ["Monoclonal anti-IgE antibody — prevents IgE binding to mast cells", "IL-5 antagonist — reduces eosinophils", "TNF-alpha inhibitor", "IL-4 receptor antagonist", "Histamine H1 receptor antagonist"], 0,
     "Omalizumab binds free IgE → prevents binding to mast cell FcεRI receptors → decreased mast cell degranulation. Used for moderate-severe allergic asthma and chronic urticaria. Subcutaneous injection every 2-4 weeks.",
     "奥马珠单抗结合游离IgE→阻止与肥大细胞受体结合→减少肥大细胞脱颗粒。用于中重度过敏性哮喘和慢性荨麻疹。每2-4周皮下注射。",
     "Omalizumab: anticuerpo anti-IgE → previene union a mastocitos. Asma alergica moderada-severa, urticaria cronica. SC cada 2-4 sem."),
    ("A patient with HIV has oral thrush and CD4 count of 180. Which opportunistic infection prophylaxis should be started?",
     ["Trimethoprim-sulfamethoxazole (TMP-SMX) for PCP", "Azithromycin for MAC", "Fluconazole for candidiasis", "Valganciclovir for CMV", "Isoniazid for TB"], 0,
     "PCP prophylaxis: started when CD4 <200 (TMP-SMX). MAC prophylaxis: CD4 <50 (azithromycin). Toxoplasmosis prophylaxis: CD4 <100 (TMP-SMX also covers). Candidiasis treated when symptomatic, not routine prophylaxis.",
     "PCP预防：CD4<200时开始（TMP-SMX）。MAC预防：CD4<50（阿奇霉素）。弓形虫预防：CD4<100（TMP-SMX也覆盖）。念珠菌病仅在出现症状时治疗。",
     "Profilaxis PCP: CD4 <200 (TMP-SMX). MAC: CD4 <50 (azitromicina). Toxoplasmosis: CD4 <100. Candidiasis: tratar sintomatico, no profilaxis rutinaria."),
    ("Which immune cell is primarily infected by HIV, and what receptor does the virus use for entry?",
     ["CD4+ T cells — CD4 receptor + CCR5/CXCR4 co-receptor", "CD8+ T cells — CD8 receptor", "B cells — CD21 receptor", "Macrophages — Fc receptor only", "Dendritic cells — MHC class II"], 0,
     "HIV infects CD4+ cells (T cells, macrophages, dendritic cells). Entry requires CD4 + co-receptor (CCR5 in early infection, CXCR4 in late). CCR5-delta32 mutation confers resistance. Maraviroc = CCR5 antagonist.",
     "HIV感染CD4+细胞。进入需要CD4+共受体（早期CCR5，晚期CXCR4）。CCR5-Δ32突变提供抗性。马拉维若=CCR5拮抗剂。",
     "VIH infecta celulas CD4+. Entrada requiere CD4 + co-receptor (CCR5 temprano, CXCR4 tardio). Mutacion CCR5-delta32 confiere resistencia."),
    ("Which immunoglobulin is found in secretions (tears, saliva, breast milk, GI/respiratory mucosa)?",
     ["IgA (dimeric, secretory component)", "IgG (monomeric, crosses placenta)", "IgM (pentameric, first response)", "IgE (binds mast cells, parasites)", "IgD (B cell receptor)"], 0,
     "Secretory IgA: dimeric IgA + J chain + secretory component → protects mucosal surfaces. Major Ig in breast milk (passive immunity). IgG crosses placenta (only Ig to do so). IgA deficiency is the most common primary immunodeficiency.",
     "分泌型IgA：二聚体IgA+J链+分泌片→保护黏膜表面。乳汁中主要Ig。IgG通过胎盘。IgA缺乏是最常见原发性免疫缺陷。",
     "IgA secretora: dimero + cadena J + componente secretor → protege mucosas. Principal Ig en leche materna. IgG cruza placenta."),
    ("Which drug used for rheumatoid arthritis is a TNF-alpha inhibitor?",
     ["Infliximab (also adalimumab, etanercept)", "Rituximab", "Tocilizumab", "Abatacept", "Anakinra"], 0,
     "TNF-alpha inhibitors: infliximab (chimeric mAb), adalimumab (human mAb), etanercept (TNFR2-Fc fusion), certolizumab, golimumab. Used for RA, IBD, psoriasis, ankylosing spondylitis. Risk: TB reactivation (test before starting).",
     "TNF-α抑制剂：英夫利西单抗、阿达木单抗、依那西普等。用于RA、IBD、银屑病等。风险：TB再激活（使用前需筛查）。",
     "Inhibidores TNF-alfa: infliximab, adalimumab, etanercept. Usos: AR, EII, psoriasis, espondilitis. Riesgo: reactivacion TB."),
    ("A newborn presents with tetany, cardiac defects, and absent thymic shadow on CXR. What is the diagnosis?",
     ["DiGeorge syndrome (22q11.2 deletion)", "SCID", "Ataxia-telangiectasia", "Wiskott-Aldrich syndrome", "Hyper-IgE syndrome"], 0,
     "DiGeorge syndrome: 22q11.2 microdeletion → abnormal 3rd/4th pharyngeal pouch development → thymic aplasia (T cell deficiency), hypoparathyroidism (hypocalcemia/tetany), cardiac defects (tetralogy of Fallot, truncus arteriosus), cleft palate.",
     "DiGeorge综合征：22q11.2微缺失→胸腺发育不良、甲状旁腺功能减退（低钙/手足抽搐）、心脏缺陷、腭裂。",
     "Sindrome DiGeorge: microdelecion 22q11.2 → aplasia timica, hipoparatiroidismo, defectos cardiacos, paladar hendido."),
]
for qq in immuno_qs:
    q(next_id, 'step1', 'Immunology', *qq); next_id += 1

# --- Genetics (15 questions) ---
genetics_qs = [
    ("A 35F has a child diagnosed with trisomy 21 (Down syndrome). Which maternal factor is most strongly associated?",
     ["Advanced maternal age (>35 years)", "Advanced paternal age", "Folic acid deficiency", "Radiation exposure", "Maternal diabetes"], 0,
     "Risk of trisomy 21 increases with maternal age due to nondisjunction during meiosis I. At age 35: 1/350; at age 45: 1/30. Screening: first trimester ultrasound (nuchal translucency) + PAPP-A + beta-hCG. Confirm with amniocentesis/CVS.",
     "21三体风险随母亲年龄增加（减数分裂I期不分离）。35岁：1/350；45岁：1/30。筛查：NT超声+PAPP-A+β-hCG。羊水穿刺/CVS确诊。",
     "Riesgo trisomia 21 aumenta con edad materna (no disyuncion meiosis I). Cribado: TN + PAPP-A + beta-hCG. Confirmacion: amniocentesis."),
    ("Marfan syndrome is caused by a mutation in which gene?",
     ["FBN1 (fibrillin-1)", "COL1A1 (collagen type I)", "COL3A1 (collagen type III)", "ELN (elastin)", "TGFBR1 (TGF-beta receptor)"], 0,
     "Marfan syndrome: FBN1 mutation → defective fibrillin → increased TGF-beta signaling. Features: tall stature, arachnodactyly, lens dislocation (upward/temporal), aortic root dilation (risk of dissection), mitral valve prolapse. AD inheritance.",
     "马凡综合征：FBN1突变→原纤蛋白缺陷→TGF-β信号增强。特征：高身材、蜘蛛指、晶状体脱位（向上）、主动脉根部扩张、二尖瓣脱垂。常染色体显性遗传。",
     "Sindrome Marfan: mutacion FBN1 → fibrilina defectuosa. Estatura alta, aracnodactilia, luxacion cristalino (arriba), dilatacion raiz aortica. Herencia AD."),
    ("Which inheritance pattern is characterized by affected individuals in every generation, with males and females equally affected?",
     ["Autosomal dominant", "Autosomal recessive", "X-linked recessive", "X-linked dominant", "Mitochondrial"], 0,
     "AD: vertical transmission (every generation), males = females affected, variable expression. AR: horizontal (siblings, skips generations), consanguinity increases risk. X-linked recessive: affected males, carrier females. Mitochondrial: maternal inheritance only.",
     "常染色体显性：每代均有患者，男女均等。常染色体隐性：同胞患病，隔代遗传，近亲婚配风险增加。X连锁隐性：男性发病，女性携带。线粒体：母系遗传。",
     "AD: transmision vertical, hombres = mujeres. AR: horizontal, consanguinidad aumenta riesgo. XL recesivo: hombres afectados. Mitocondrial: solo materna."),
    ("Cystic fibrosis is caused by which type of mutation in the CFTR gene?",
     ["Deletion of phenylalanine at position 508 (ΔF508)", "Nonsense mutation", "Trinucleotide repeat expansion", "Splice-site mutation", "Missense mutation"], 0,
     "CF: ΔF508 (3-bp deletion in CFTR) is the most common mutation (70% in Caucasians). CFTR = Cl- channel. AR inheritance. Features: thick secretions, recurrent pneumonia, pancreatic insufficiency, male infertility, elevated sweat chloride.",
     "CF：ΔF508是CFTR基因最常见突变（高加索人中70%）。CFTR=氯离子通道。常染色体隐性遗传。特征：黏稠分泌物、反复肺炎、胰腺功能不全、男性不育、汗液氯离子升高。",
     "FQ: mutacion mas comun ΔF508 (delecion 3pb en CFTR). Herencia AR. Secreciones espesas, neumonia recurrente, insuficiencia pancreatica."),
    ("What is the genetic mechanism of Huntington disease?",
     ["CAG trinucleotide repeat expansion in HTT gene", "CGG repeat expansion in FMR1 gene", "CTG repeat expansion in DMPK gene", "GAA repeat expansion in FXN gene", "Missense mutation in FGFR3 gene"], 0,
     "HD: AD inheritance, CAG repeat expansion in huntingtin gene (chr 4) → toxic gain of function. Anticipation: earlier onset in successive generations (paternal transmission). CAG repeats: <26 normal, 27-35 intermediate, 36-39 reduced penetrance, >40 full penetrance.",
     "亨廷顿病：AD遗传，HTT基因CAG重复扩增→毒性功能获得。遗传早现：逐代发病年龄提前（父系传递）。CAG重复<26正常，>40完全外显。",
     "EH: herencia AD, expansion repeticiones CAG en gen huntingtina → ganancia toxica. Anticipacion: inicio mas temprano en generaciones sucesivas."),
    ("A child with developmental delay has a 'happy' demeanor, inappropriate laughter, ataxia, and seizures. Which genetic disorder?",
     ["Angelman syndrome", "Prader-Willi syndrome", "Fragile X syndrome", "Rett syndrome", "Williams syndrome"], 0,
     "Angelman syndrome: maternal deletion 15q11-13 (UBE3A), 'happy puppet' — happy demeanor, ataxia, seizures, severe intellectual disability. Prader-Willi: paternal deletion same region → hyperphagia, obesity, hypotonia. Both are imprinting disorders.",
     "Angelman综合征：母源15q11-13缺失，快乐木偶综合征——欣快、共济失调、癫痫。Prader-Willi：父源同区域缺失→食欲过盛、肥胖、肌张力低下。两者的印记障碍。",
     "Angelman: delecion materna 15q11-13 → feliz, ataxia, convulsiones. Prader-Willi: delecion paterna misma region → hiperfagia, obesidad. Trastornos de impronta."),
    ("Which finding on karyotype would confirm Turner syndrome?",
     ["45,X", "47,XXY", "47,XX,+21", "47,XYY", "46,XY, del(5p)"], 0,
     "Turner syndrome: 45,X (monosomy X), most common sex chromosome abnormality in females. Features: short stature, webbed neck, lymphedema of hands/feet, coarctation of aorta, streak ovaries, primary amenorrhea. Only monosomy compatible with life.",
     "Turner综合征：45,X，女性最常见性染色体异常。特征：身材矮小、蹼颈、手足淋巴水肿、主动脉缩窄、条索状卵巢、原发性闭经。唯一可存活的单体性。",
     "Turner: 45,X, anomalia cromosomas sexuales mas comun en mujeres. Talla baja, cuello palmeado, coartacion aortica, ovarios en cintilla."),
    ("A newborn has a cat-like cry (high-pitched), microcephaly, and severe intellectual disability. What chromosomal abnormality?",
     ["Cri-du-chat syndrome (5p deletion)", "Wolf-Hirschhorn syndrome (4p deletion)", "Patau syndrome (trisomy 13)", "Edwards syndrome (trisomy 18)", "Klinefelter syndrome (47,XXY)"], 0,
     "Cri-du-chat: deletion 5p → characteristic cat-like cry in infancy (laryngeal maldevelopment), microcephaly, severe ID. Wolf-Hirschhorn: 4p deletion → 'Greek warrior helmet' facies, seizures. Patau: trisomy 13; Edwards: trisomy 18.",
     "猫叫综合征：5p缺失→婴儿期特征性猫叫样哭声、小头畸形、严重智力障碍。",
     "Cri-du-chat: delecion 5p → llanto como maullido de gato, microcefalia, DI severa. Wolf-Hirschhorn: delecion 4p."),
    ("Achondroplasia is caused by a gain-of-function mutation in which gene?",
     ["FGFR3 (fibroblast growth factor receptor 3)", "FBN1 (fibrillin)", "COL2A1 (collagen type II)", "COMP (cartilage oligomeric matrix protein)", "GNAS1"], 0,
     "Achondroplasia: activating mutation in FGFR3 → constitutively active → inhibits chondrocyte proliferation → short limbs (rhizomelic), frontal bossing, trident hands. AD inheritance, most cases are new mutations (associated with advanced paternal age).",
     "软骨发育不全：FGFR3激活突变→组成性活性→抑制软骨细胞增殖→短肢（近端型）、前额突出、三叉手。AD遗传，多数为新发突变（与高龄父亲相关）。",
     "Acondroplasia: mutacion activadora FGFR3 → inhibe proliferacion condrocitos → miembros cortos, frente prominente. Herencia AD, mayoria mutaciones de novo."),
    ("What is the recurrence risk for an autosomal recessive disorder when both parents are carriers?",
     ["25% affected, 50% carrier, 25% unaffected non-carrier", "50% affected, 50% carrier", "100% affected", "25% affected, 75% unaffected non-carrier", "50% affected, 25% carrier, 25% unaffected"], 0,
     "AR: both parents carriers (Aa x Aa) → 25% aa (affected), 50% Aa (carrier), 25% AA (unaffected). AD: one parent affected (Aa x aa) → 50% affected, 50% unaffected. XR: carrier mother → 50% sons affected.",
     "AR：双亲携带者→25%患病，50%携带，25%正常。AD：一方患病→50%患病。XR：携带者母亲→50%儿子患病。",
     "AR: ambos padres portadores → 25% afectado, 50% portador, 25% sano. AD: un padre afectado → 50% afectado. XR: madre portadora → 50% hijos afectados."),
    ("Which genetic testing method can detect copy number variations (CNVs) across the entire genome?",
     ["Chromosomal microarray (CMA)", "Karyotype (G-banding)", "FISH (fluorescence in situ hybridization)", "Sanger sequencing", "PCR"], 0,
     "CMA detects submicroscopic CNVs (deletions and duplications) genome-wide. First-line for developmental delay, autism, congenital anomalies. Resolution ~50-100 kb (vs karyotype ~5-10 Mb). Cannot detect balanced translocations (need karyotype).",
     "CMA可检测全基因组亚显微CNVs。发育迟缓、自闭症和先天异常的一线检查。分辨率约50-100 kb。不能检测平衡易位（需核型分析）。",
     "CMA detecta CNVs sub-microscopicos en todo genoma. Primera linea retraso desarrollo, autismo. Resolucion ~50-100 kb. No detecta translocaciones balanceadas."),
    ("A 4M boy has intellectual disability, large ears, macroorchidism (post-pubertal), and hyperextensible joints. What is the diagnosis?",
     ["Fragile X syndrome", "Klinefelter syndrome", "Prader-Willi syndrome", "Noonan syndrome", "Beckwith-Wiedemann syndrome"], 0,
     "Fragile X: FMR1 gene CGG repeat expansion (>200) → methylation and silencing. Most common inherited cause of intellectual disability. Features: large ears, long face, macroorchidism, hyperextensible joints, mitral valve prolapse, autism-like features.",
     "脆性X综合征：FMR1基因CGG重复扩增（>200）→甲基化和沉默。最常见的遗传性智力障碍。特征：大耳、长脸、巨睾、关节过伸、二尖瓣脱垂。",
     "X fragil: expansion CGG >200 en FMR1 → metilacion y silenciamiento. Causa hereditaria mas comun DI. Orejas grandes, cara larga, macroorquidia."),
    ("A newborn girl has lymphedema of hands and feet, webbed neck, and coarctation of the aorta. Karyotype shows 45,X. What is the most likely cardiovascular finding?",
     ["Coarctation of the aorta + bicuspid aortic valve", "Tetralogy of Fallot", "Transposition of great arteries", "Ventricular septal defect", "Patent ductus arteriosus"], 0,
     "Turner syndrome (45,X): coarctation of aorta and bicuspid aortic valve are the most common cardiac findings. Also increased risk of aortic dissection. Short stature treated with growth hormone. Estrogen for puberty induction.",
     "Turner综合征心血管表现：主动脉缩窄+二叶式主动脉瓣最常见。主动脉夹层风险增加。GH治疗矮小。雌激素诱导青春期。",
     "Turner cardiovascular: coartacion aortica + valvula aortica bicuspide mas comunes. Riesgo diseccion aortica. GH para talla baja."),
    ("What is the genetic cause of Duchenne muscular dystrophy?",
     ["Dystrophin gene mutation (Xp21) — X-linked recessive", "Myotonin protein kinase mutation — AD", "Lamin A/C mutation — AD", "Dysferlin mutation — AR", "Emerin mutation — XR"], 0,
     "DMD: dystrophin gene mutation (Xp21) → absent dystrophin → progressive muscle weakness (calf pseudohypertrophy, Gower sign). Becker MD: partially functional dystrophin → milder course. Elevated CK (10-100x). X-linked recessive.",
     "DMD：抗肌萎缩蛋白基因突变（Xp21）→抗肌萎缩蛋白缺失→进行性肌无力。CK升高10-100倍。X连锁隐性遗传。BMD病程较轻。",
     "DMD: mutacion gen distrofina (Xp21) → ausencia distrofina → debilidad progresiva. CK elevada 10-100x. Herencia XR. Becker: curso mas leve."),
    ("Which disease demonstrates anticipation through expansion of CTG repeats in the DMPK gene?",
     ["Myotonic dystrophy type 1", "Huntington disease", "Fragile X syndrome", "Friedreich ataxia", "Spinocerebellar ataxia type 3"], 0,
     "Myotonic dystrophy type 1 (DM1): CTG repeat expansion in DMPK gene (chr 19) → anticipation (worsening in successive generations). Features: myotonia, distal weakness, cataracts, cardiac conduction defects, frontal balding, insulin resistance.",
     "强直性肌营养不良1型：DMPK基因CTG重复扩增→遗传早现。特征：肌强直、远端肌无力、白内障、心脏传导异常、额秃、胰岛素抵抗。",
     "Distrofia miotonica tipo 1: expansion CTG en DMPK → anticipacion. Miotonia, debilidad distal, cataratas, defectos conduccion cardiaca."),
]
for qq in genetics_qs:
    q(next_id, 'step1', 'Genetics', *qq); next_id += 1

# --- Neurology (10 questions) ---
neuro_qs_step1 = [
    ("Which artery is most commonly involved in ischemic stroke affecting the motor and sensory cortex of the lower limb?",
     ["Anterior cerebral artery (ACA)", "Middle cerebral artery (MCA)", "Posterior cerebral artery (PCA)", "Basilar artery", "Vertebral artery"], 0,
     "ACA supplies medial surface of frontal/parietal lobes → contralateral leg motor/sensory deficit. MCA supplies lateral surface → face/arm > leg. PCA supplies occipital lobe → visual field defects. Homunculus: leg = medial/ACA, face/arm = lateral/MCA.",
     "ACA供应额顶叶内侧面→对侧下肢运动感觉障碍。MCA供应外侧面→面部/上肢>下肢。PCA供应枕叶→视野缺损。",
     "ACA irriga superficie medial frontal/parietal → deficit motor/sensorial pierna contralateral. ACM: cara/brazo > pierna. ACP: defectos campo visual."),
    ("A 70M has resting tremor, rigidity, bradykinesia, and postural instability. Which neurotransmitter system is primarily deficient?",
     ["Dopamine (substantia nigra pars compacta)", "Serotonin (raphe nuclei)", "Acetylcholine (basal forebrain)", "Norepinephrine (locus coeruleus)", "GABA (striatum)"], 0,
     "Parkinson disease: dopaminergic neuron loss in substantia nigra pars compacta → dopamine deficiency in striatum. Lewy bodies (alpha-synuclein). Treatment: levodopa/carbidopa, dopamine agonists, MAO-B inhibitors.",
     "帕金森病：黑质致密部多巴胺神经元丧失→纹状体多巴胺缺乏。路易小体（α-突触核蛋白）。治疗：左旋多巴/卡比多巴、多巴胺激动剂、MAO-B抑制剂。",
     "Parkinson: perdida neuronas dopaminergicas sustancia negra pars compacta → deficit dopamina estriado. Cuerpos Lewy (alfa-sinucleina). Tratamiento: levodopa/carbidopa."),
    ("A 25F has episodes of unilateral throbbing headache with photophobia, phonophobia, and nausea. She sees flashing lights before the headache. Diagnosis?",
     ["Migraine with aura", "Tension-type headache", "Cluster headache", "Trigeminal neuralgia", "Giant cell arteritis"], 0,
     "Migraine with aura: visual aura (scintillating scotoma) → throbbing unilateral headache + photophobia, phonophobia, nausea. Lasts 4-72 hours. Triggers: stress, menses, foods. Acute treatment: triptans, NSAIDs. Prophylaxis: beta-blockers, topiramate.",
     "有先兆偏头痛：视觉先兆（闪烁暗点）→单侧搏动性头痛+畏光畏声恶心。持续4-72小时。急性治疗：曲普坦、NSAIDs。预防：β受体阻滞剂、托吡酯。",
     "Migrana con aura: escotoma centelleante → cefalea pulsati unilateral + fotofobia, fonofobia, nauseas. Tratamiento agudo: triptanes. Profilaxis: beta-bloqueantes."),
    ("A patient has 'pill-rolling' tremor at rest that improves with intentional movement. What type of tremor is this?",
     ["Parkinsonian resting tremor (3-5 Hz)", "Essential tremor (6-12 Hz, postural/action)", "Cerebellar intention tremor", "Physiologic tremor", "Dystonic tremor"], 0,
     "Parkinsonian tremor: resting, 'pill-rolling,' 3-5 Hz, decreases with voluntary movement. Essential tremor: bilateral postural/action tremor, 6-12 Hz, improves with alcohol, familial. Cerebellar: intention tremor, worse at end of movement.",
     "帕金森震颤：静止性、搓丸样、3-5 Hz，随意运动时减轻。特发性震颤：双侧姿势性/动作性、6-12 Hz、饮酒后改善。小脑性：意向性震颤。",
     "Temblor parkinsoniano: reposo, cuenta-monedas, 3-5 Hz. Temblor esencial: postural/accion, 6-12 Hz, mejora alcohol. Cerebeloso: intencion."),
    ("Which seizure type involves impaired consciousness with automatisms (lip-smacking, picking) and originates in the temporal lobe?",
     ["Focal impaired awareness seizure (complex partial)", "Generalized tonic-clonic seizure", "Absence seizure", "Myoclonic seizure", "Atonic seizure"], 0,
     "Focal impaired awareness (complex partial): temporal lobe origin, impaired consciousness, automatisms (lip-smacking, picking), aura may precede. Generalized tonic-clonic: loss of consciousness + convulsions. Absence: brief staring spells in children.",
     "局灶性意识障碍性发作：颞叶起源，意识障碍，自动症（吧唧嘴、摸索动作），可能有先兆。",
     "Crisis focal con alteracion conciencia: origen temporal, automatismos (chasquido labios), aura posible. Generalizada tonico-clonica: perdida conciencia + convulsiones."),
    ("A 65F with atrial fibrillation suddenly develops right-sided weakness and aphasia. CT head is negative. What is the next step?",
     ["tPA (alteplase) if within 4.5 hours and no contraindications", "Aspirin immediately", "Wait for MRI results", "Heparin infusion", "Observation only"], 0,
     "Acute ischemic stroke in AF patient: tPA within 4.5 hours of symptom onset (after ruling out hemorrhage on CT). Mechanical thrombectomy for large vessel occlusion within 24 hours. Anticoagulation for secondary prevention (not acutely).",
     "急性缺血性卒中：发病4.5小时内tPA溶栓。大血管闭塞24小时内机械取栓。二级预防抗凝（非急性期）。",
     "Ictus isquemico agudo: tPA en <4.5h (descartar hemorragia). Trombectomia mecanica <24h para oclusion gran vaso. Anticoagulacion prevencion secundaria."),
    ("Which type of aphasia is characterized by fluent speech with paraphasias, impaired comprehension, and poor repetition?",
     ["Wernicke aphasia", "Broca aphasia", "Conduction aphasia", "Global aphasia", "Transcortical motor aphasia"], 0,
     "Wernicke: fluent, paraphasic speech + impaired comprehension + poor repetition. Lesion: superior temporal gyrus. Broca: non-fluent + intact comprehension + poor repetition. Conduction: fluent + intact comprehension + poor repetition (arcuate fasciculus).",
     "Wernicke失语：流利性言语伴错语+理解受损+复述差。病灶：颞上回。Broca：非流利+理解好+复述差。传导性：流利+理解好+复述差。",
     "Afasia Wernicke: fluente, parafasias + comprension alterada + repeticion pobre. Broca: no fluente + comprension intacta. Conduccion: fluente + comprension intacta + repeticion pobre."),
    ("A 45M has progressive dementia, myoclonus, and periodic sharp-wave complexes on EEG. What is the most likely diagnosis?",
     ["Creutzfeldt-Jakob disease (CJD)", "Alzheimer disease", "Frontotemporal dementia", "Dementia with Lewy bodies", "Vascular dementia"], 0,
     "CJD: rapidly progressive dementia + myoclonus + periodic sharp-wave complexes on EEG + 14-3-3 protein in CSF. Spongiform degeneration on pathology. Prion disease. MRI shows cortical ribboning and basal ganglia hyperintensity on DWI.",
     "CJD：快速进展性痴呆+肌阵挛+EEG周期性尖波+CSF中14-3-3蛋白。病理示海绵状变性。朊病毒病。MRI DWI显示皮质带和基底节高信号。",
     "ECJ: demencia rapidamente progresiva + mioclonias + complejos periodicos EEG + proteina 14-3-3. Degeneracion espongiforme. Enfermedad prionica."),
    ("What is the mechanism of action of triptans in acute migraine treatment?",
     ["5-HT1B/1D receptor agonists → vasoconstriction + inhibition of trigeminal CGRP release", "Dopamine antagonists", "COX-2 inhibitors", "CGRP receptor antagonists (gepants)", "GABA agonists"], 0,
     "Triptans (sumatriptan): 5-HT1B/1D agonists → cranial vasoconstriction, inhibition of trigeminal nerve CGRP release. Contraindicated in CAD, stroke, uncontrolled HTN, hemiplegic/basilar migraine. CGRP antagonists (gepants) are newer alternatives.",
     "曲普坦：5-HT1B/1D激动剂→脑血管收缩、抑制三叉神经CGRP释放。禁用于CAD、卒中、未控制高血压、偏瘫/基底型偏头痛。",
     "Triptanes: agonistas 5-HT1B/1D → vasoconstriccion craneal + inhiben liberacion CGRP trigeminal. Contraindicado EAC, ictus, HTA no controlada."),
    ("A patient develops ascending symmetrical weakness starting in the legs 2 weeks after a diarrheal illness. CSF shows albuminocytologic dissociation. What is the diagnosis?",
     ["Guillain-Barre syndrome (AIDP)", "Myasthenia gravis", "Multiple sclerosis", "Botulism", "Lambert-Eaton myasthenic syndrome"], 0,
     "GBS: ascending symmetric weakness, areflexia, albuminocytologic dissociation (high protein, normal WBC in CSF). Often post-infectious (Campylobacter jejuni most common). Treatment: IVIG or plasmapheresis. Monitor respiratory function (FVC).",
     "GBS：上升性对称性肌无力+腱反射消失+CSF蛋白细胞分离。常为感染后（空肠弯曲杆菌最多见）。治疗：IVIG或血浆置换。监测呼吸功能。",
     "SGB: debilidad ascendente simetrica + arreflexia + disociacion albumino-citologica. Posinfeccioso (C. jejuni). Tratamiento: IgIV o plasmaferesis."),
]
for qq in neuro_qs_step1:
    q(next_id, 'step1', 'Neurology', *qq); next_id += 1

# --- Internal Medicine Step 1 (15 questions) ---
im_qs_step1 = [
    ("A 55M has polyuria, polydipsia, fasting glucose of 240 mg/dL. Which test confirms the diagnosis of diabetes mellitus?",
     ["Fasting glucose >=126 mg/dL on two separate occasions OR HbA1c >=6.5%", "Random glucose >200 with symptoms", "Oral glucose tolerance test only", "Urine glucose", "Fructosamine level"], 0,
     "DM diagnosis: fasting glucose >=126 (x2), OR HbA1c >=6.5%, OR OGTT 2-hr >=200, OR random glucose >=200 + symptoms. Type 1: autoimmune (anti-GAD, anti-islet), young, DKA risk. Type 2: insulin resistance, older, obese, strong family history.",
     "DM诊断：空腹血糖>=126或HbA1c>=6.5%或OGTT 2小时>=200或有症状+随机血糖>=200。T1DM：自身免疫性。T2DM：胰岛素抵抗。",
     "Diagnostico DM: glucemia ayuno >=126 o HbA1c >=6.5% o OGTT 2h >=200. DM1: autoinmune. DM2: resistencia insulina."),
    ("DKA (diabetic ketoacidosis) is characterized by which triad?",
     ["Hyperglycemia, anion gap metabolic acidosis, ketonemia", "Hyperglycemia, hyperosmolarity, severe dehydration", "Hypoglycemia, metabolic alkalosis, ketonuria", "Hyperglycemia, normal pH, mild ketosis", "Hypoglycemia, lactic acidosis, ketonemia"], 0,
     "DKA: hyperglycemia (>250), anion-gap metabolic acidosis, ketones in blood/urine. Type 1 DM > Type 2. HHS: severe hyperglycemia (>600), hyperosmolarity, no/minimal ketosis. DKA treatment: fluids, insulin, potassium (even if normal K+).",
     "DKA：高血糖（>250）+阴离子间隙代谢性酸中毒+酮血症。T1DM多见。HHS：严重高血糖（>600）+高渗透压+无或少量酮体。DKA治疗：补液+胰岛素+补钾。",
     "CAD: hiperglucemia (>250) + acidosis metabolica anion gap + cetonemia. EHH: hiperglucemia severa (>600) + hiperosmolaridad. Tratamiento: liquidos + insulina + potasio."),
    ("Which thyroid cancer has the best prognosis?",
     ["Papillary thyroid carcinoma", "Follicular thyroid carcinoma", "Medullary thyroid carcinoma", "Anaplastic thyroid carcinoma", "Thyroid lymphoma"], 0,
     "Prognosis (best to worst): Papillary > Follicular > Medullary > Anaplastic. Papillary: most common (80%), spreads via lymphatics, psammoma bodies, 'Orphan Annie' nuclei. Follicular: hematogenous spread. Medullary: from C-cells, calcitonin, RET proto-oncogene.",
     "预后（最好到最差）：乳头状>滤泡状>髓样>未分化。乳头状：最常见（80%），淋巴转移，砂粒体。滤泡状：血行转移。髓样：C细胞，降钙素，RET基因。",
     "Pronostico: papilar > folicular > medular > anaplasico. Papilar: 80%, diseminacion linfatica, cuerpos psammoma. Medular: celulas C, calcitonina, RET."),
    ("A 65F has gradual onset of fatigue, weight gain, cold intolerance, and constipation. TSH is elevated, free T4 is low. Diagnosis?",
     ["Primary hypothyroidism (most likely Hashimoto thyroiditis)", "Secondary hypothyroidism (pituitary)", "Euthyroid sick syndrome", "Subclinical hypothyroidism", "Thyroid hormone resistance"], 0,
     "Primary hypothyroidism: elevated TSH + low free T4. Most common cause = Hashimoto (anti-TPO, anti-thyroglobulin). Secondary: low TSH + low T4 (pituitary). Subclinical: elevated TSH + normal T4. Treatment: levothyroxine.",
     "原发性甲减：TSH升高+T4降低。最常见原因=桥本甲状腺炎。继发性：TSH低+T4低。亚临床：TSH高+T4正常。治疗：左甲状腺素。",
     "Hipotiroidismo primario: TSH elevada + T4 baja. Causa mas comun: Hashimoto. Secundario: TSH baja + T4 baja. Subclinico: TSH elevada + T4 normal."),
    ("Which antiarrhythmic drug class is amiodarone?",
     ["Class III (K+ channel blocker) — also has Class I, II, IV effects", "Class I (Na+ channel blocker)", "Class II (beta-blocker)", "Class IV (Ca2+ channel blocker)", "Class V (miscellaneous)"], 0,
     "Amiodarone: primarily Class III (prolongs repolarization/APD via K+ channel blockade). Also has Class I, II, IV effects. Used for atrial fibrillation, ventricular arrhythmias. Adverse effects: pulmonary fibrosis, thyroid dysfunction, liver toxicity, corneal deposits, blue skin.",
     "胺碘酮：主要是III类（延长复极/动作电位时程）。兼有I、II、IV类效应。不良反应：肺纤维化、甲状腺功能障碍、肝毒性、角膜沉积、蓝灰色皮肤。",
     "Amiodarona: clase III (prolonga repolarizacion). Tambien efectos clase I, II, IV. Efectos: fibrosis pulmonar, disfuncion tiroidea, toxicidad hepatica, depositos corneales."),
    ("Which electrolyte abnormality is most commonly associated with digoxin toxicity?",
     ["Hypokalemia", "Hyperkalemia", "Hypercalcemia", "Hyponatremia", "Hypomagnesemia"], 0,
     "Hypokalemia increases digoxin binding to Na+/K+ ATPase → increased toxicity. Also hypomagnesemia increases sensitivity. Digoxin toxicity: nausea, visual changes (yellow halos, scotomas), arrhythmias (atrial tachycardia with block, bidirectional VT). Treatment: digoxin immune Fab.",
     "低钾血症增加地高辛与Na+/K+ ATP酶结合→毒性增加。地高辛中毒：恶心、视觉变化、心律失常。治疗：地高辛免疫Fab。",
     "Hipokalemia aumenta union digoxina a Na+/K+ ATPasa → mayor toxicidad. Toxicidad: nauseas, cambios visuales, arritmias. Tratamiento: Fab anti-digoxina."),
    ("A 70M with COPD develops worsening dyspnea and hypercapnic respiratory failure. What is the target oxygen saturation?",
     ["88-92% (to avoid suppressing hypoxic drive)", "94-98% (same as non-COPD patients)", ">98%", "85-88%", "<85%"], 0,
     "COPD patients may rely on hypoxic drive for ventilation. Excess O2 can suppress respiratory drive → worsening hypercapnia. Target SpO2 88-92%. If consciousness deteriorates or PaCO2 rises significantly, consider NIV (BiPAP).",
     "COPD患者可能依赖低氧驱动通气。过高氧疗会抑制呼吸驱动→加重高碳酸血症。目标SpO2 88-92%。如意识恶化考虑无创通气。",
     "EPOC puede depender impulso hipoxico. Exceso O2 suprime impulso → empeora hipercapnia. SpO2 objetivo 88-92%. Considerar VNI si deterioro."),
    ("A 60M on warfarin for atrial fibrillation has an INR of 8.0 with no bleeding. What is the management?",
     ["Hold warfarin + give oral vitamin K", "FFP transfusion", "Prothrombin complex concentrate (PCC)", "Continue warfarin, recheck in 1 week", "IV vitamin K only"], 0,
     "INR >10 or 4.5-10 without bleeding: hold warfarin + low-dose oral vitamin K (1-2.5 mg). With ANY bleeding: hold warfarin + IV vitamin K + PCC/FFP. With life-threatening bleeding: PCC + IV vitamin K. Restart warfarin when INR therapeutic.",
     "INR>10或4.5-10无出血：暂停华法林+口服低剂量维生素K。任何出血：暂停+IV维生素K+PCC/FFP。危及生命出血：PCC+IV维生素K。",
     "INR >10 o 4.5-10 sin sangrado: suspender warfarina + vitamina K oral. Con sangrado: IV vitamina K + PCC. Sangrado amenazante: PCC + IV vitamina K."),
    ("Which finding on urinalysis is most indicative of glomerular bleeding (nephritic syndrome)?",
     ["Dysmorphic RBCs and RBC casts", "WBC casts", "Hyaline casts", "Fatty casts (oval fat bodies)", "Waxy casts"], 0,
     "Nephritic: dysmorphic RBCs + RBC casts (glomerular bleeding). Nephrotic: fatty casts, oval fat bodies (lipiduria), massive proteinuria. WBC casts: pyelonephritis, interstitial nephritis. Hyaline casts: normal/dehydration. Waxy casts: chronic renal failure.",
     "肾炎：畸形红细胞+红细胞管型。肾病：脂肪管型、卵圆脂肪小体、大量蛋白尿。白细胞管型：肾盂肾炎。蜡样管型：慢性肾衰竭。",
     "Nefritico: hematies dismorficos + cilindros hematicos. Nefrotico: cilindros grasos, cuerpos grasos ovales. Leucocitarios: pielonefritis. Cerosos: IRC."),
    ("A 50M with cirrhosis develops ascites. Serum-ascites albumin gradient (SAAG) is 1.8 g/dL. What type of ascites?",
     ["Portal hypertensive ascites (SAAG >=1.1)", "Non-portal hypertensive (SAAG <1.1)", "Chylous ascites", "Pancreatic ascites", "Nephrogenic ascites"], 0,
     "SAAG = serum albumin - ascites albumin. SAAG >=1.1 = portal hypertension (cirrhosis, CHF, Budd-Chiari). SAAG <1.1 = peritoneal process (malignancy, infection, pancreatitis, nephrotic). Treatment: sodium restriction, diuretics (spironolactone + furosemide).",
     "SAAG >=1.1 = 门脉高压性（肝硬化、心衰、Budd-Chiari）。SAAG <1.1 = 腹膜过程。治疗：限钠+利尿剂（螺内酯+呋塞米）。",
     "GASA >=1.1 = hipertension portal (cirrosis, ICC, Budd-Chiari). <1.1 = proceso peritoneal. Tratamiento: restriccion sodio + diureticos."),
    ("First-line treatment for acute gout attack includes which medications?",
     ["NSAIDs, colchicine, or glucocorticoids", "Allopurinol", "Febuxostat", "Probenecid", "Pegloticase"], 0,
     "Acute gout: NSAIDs, colchicine (best within 24h), or steroids. Do NOT start allopurinol during acute attack (may worsen). Urate-lowering (allopurinol, febuxostat) started after attack resolves with prophylaxis. Target uric acid <6 mg/dL (<5 if tophi).",
     "急性痛风：NSAIDs、秋水仙碱或激素。急性期不要开始别嘌醇。降尿酸治疗在发作缓解后开始，目标尿酸<6 mg/dL。",
     "Gota aguda: AINEs, colchicina o corticoides. NO iniciar alopurinol en ataque agudo. Hipouricemiante tras resolucion, objetivo <6 mg/dL."),
    ("A patient with STEMI has ST elevations in leads II, III, aVF. Which coronary artery is likely occluded?",
     ["Right coronary artery (RCA)", "Left anterior descending (LAD)", "Left circumflex (LCx)", "Left main coronary artery", "Posterior descending artery"], 0,
     "Inferior MI (II, III, aVF) → RCA (80%) or LCx (20%). Anterior MI (V1-V4) → LAD. Lateral MI (I, aVL, V5-V6) → LCx. Posterior MI → ST depression V1-V3 + tall R waves. RV infarction: right-sided leads V4R → hypotension, clear lungs, elevated JVP.",
     "下壁MI（II、III、aVF）→RCA（80%）或LCx（20%）。前壁MI（V1-V4）→LAD。侧壁MI（I、aVL、V5-V6）→LCx。",
     "IAM inferior (II, III, aVF) → RCA (80%) o LCx (20%). Anterior (V1-V4) → DA. Lateral (I, aVL, V5-V6) → Cx."),
    ("A 45F has elevated blood pressure (150/95) on 3 separate readings. Labs: normal renal function, normal electrolytes. What is the first-line medication?",
     ["Thiazide diuretic, ACE inhibitor, ARB, or CCB", "Beta-blocker (first-line in hypertension)", "Alpha-blocker", "Loop diuretic", "Central alpha-2 agonist"], 0,
     "First-line HTN: thiazide diuretic, ACEi/ARB, or CCB. Beta-blockers no longer first-line (reserved for specific indications like CAD, HF, post-MI). Target BP <130/80. JNC 8: <140/90 in uncomplicated, <130/80 in high-risk.",
     "一线降压药：噻嗪类利尿剂、ACEi/ARB或CCB。β阻滞剂不再一线（仅用于特定适应症如CAD、心衰、心梗后）。目标血压<130/80。",
     "Primera linea HTA: tiazida, IECA/ARA-II o BCC. Beta-bloqueantes ya no primera linea. Objetivo PA <130/80."),
    ("A diabetic patient has isolated systolic hypertension (160/70). Which medication is most appropriate?",
     ["Any first-line agent — thiazide, CCB, or ACEi/ARB", "Beta-blocker specifically", "Alpha-blocker", "Only lifestyle modifications", "Loop diuretic"], 0,
     "Isolated systolic HTN is common in elderly (increased arterial stiffness). Treatment same as essential HTN: thiazide, CCB, ACEi/ARB. SHEP trial showed benefit of treating ISH. Avoid excessive diastolic lowering in elderly with CAD.",
     "单纯收缩期高血压在老年人中常见。治疗同原发性高血压。SHEP研究表明治疗ISH有益。老年CAD患者避免过度降低舒张压。",
     "HTA sistolica aislada comun en ancianos. Tratamiento igual que HTA esencial. Evitar descenso excesivo diastolica en ancianos con EAC."),
    ("Which class of antihypertensive is preferred in patients with diabetes and proteinuria?",
     ["ACE inhibitor or ARB", "Thiazide diuretic", "Beta-blocker", "Calcium channel blocker", "Alpha-blocker"], 0,
     "ACEi/ARB: first-line in diabetic nephropathy — reduces proteinuria and slows CKD progression via efferent arteriole dilation (decreased intraglomerular pressure). Monitor K+ and Cr. Contraindicated in bilateral renal artery stenosis.",
     "ACEi/ARB：糖尿病肾病一线用药——扩张出球小动脉→降低肾小球内压→减少蛋白尿、延缓CKD进展。监测血钾和肌酐。双侧肾动脉狭窄禁用。",
     "IECA/ARA-II: primera linea nefropatia diabetica → reducen proteinuria, frenan progresion ERC. Monitorizar K+ y Cr. Contraindicado estenosis bilateral arteria renal."),
]
for qq in im_qs_step1:
    q(next_id, 'step1', 'Internal Medicine', *qq); next_id += 1

# ===========================================================
# STEP 2 CK — 250 Questions
# ===========================================================

# --- Internal Medicine Step 2 (40 questions) ---
im_qs_step2 = [
    ("A 65M with 40-pack-year smoking history presents with progressive dyspnea, chronic productive cough, and wheezing. CXR shows hyperinflation and flattened diaphragms. PFTs show FEV1/FVC <0.70 with decreased DLCO. Diagnosis?",
     ["COPD (chronic obstructive pulmonary disease)", "Asthma", "Bronchiectasis", "Interstitial lung disease", "Congestive heart failure"], 0,
     "COPD diagnosis: FEV1/FVC <0.70 post-bronchodilator. Decreased DLCO distinguishes emphysema from asthma (DLCO normal in asthma). Gold stages based on FEV1% predicted. Management: smoking cessation, bronchodilators, inhaled corticosteroids, pulmonary rehab.",
     "COPD诊断：支气管扩张剂后FEV1/FVC<0.70。DLCO降低区分肺气肿与哮喘（哮喘DLCO正常）。治疗：戒烟+支气管扩张剂+ICS+肺康复。",
     "EPOC: FEV1/FVC <0.70 post-broncodilatador. DLCO disminuida distingue enfisema de asma. Tratamiento: cese tabaquismo + broncodilatadores + CI + rehabilitacion."),
    ("A 55F with diabetes and hypertension develops acute-onset severe chest pain radiating to the back. CXR shows widened mediastinum. What is the most likely diagnosis?",
     ["Aortic dissection", "Acute myocardial infarction", "Pulmonary embolism", "Tension pneumothorax", "Pericarditis"], 0,
     "Aortic dissection: severe tearing chest pain radiating to back, widened mediastinum on CXR, pulse deficits, BP differential between arms. Stanford A: ascending aorta (surgery). Stanford B: descending only (medical — beta-blockers, BP control). CT angiography confirms.",
     "主动脉夹层：剧烈撕裂样胸痛放射背部，CXR纵隔增宽，脉搏不对称。Stanford A型（升主动脉）手术。Stanford B型（仅降主动脉）药物治疗。CTA确诊。",
     "Diseccion aortica: dolor toracico desgarrante a espalda, mediastino ensanchado. Stanford A (ascendente): cirugia. Stanford B (descendente): medico. Angio-TAC confirma."),
    ("A 70F presents with syncope, chest pain, and harsh systolic crescendo-decrescendo murmur at right upper sternal border radiating to carotids. Diagnosis?",
     ["Aortic stenosis", "Mitral regurgitation", "Aortic regurgitation", "Mitral stenosis", "Hypertrophic cardiomyopathy"], 0,
     "AS: syncope + angina + dyspnea = classic triad. Crescendo-decrescendo systolic murmur at RUSB radiating to carotids. Pulsus parvus et tardus (slow-rising carotid pulse). Echo confirms. Symptomatic AS needs AVR. Asymptomatic: watchful waiting.",
     "AS：晕厥+心绞痛+呼吸困难三联征。胸骨右缘第2肋间递增递减型收缩期杂音，向颈动脉传导。有症状AS需要AVR。",
     "EA: sincope + angina + disnea. Soplo sistolico crescendo-decrescendo en BPD derecho irradiando carotidas. EA sintomatica: reemplazo valvular."),
    ("A 60F has acute unilateral leg swelling and pain after a long flight. Doppler ultrasound shows DVT in the left popliteal vein. She is hemodynamically stable. Treatment?",
     ["Anticoagulation (LMWH or DOAC)", "Thrombolysis", "IVC filter placement", "Compression stockings only", "Observation and repeat ultrasound in 1 week"], 0,
     "Proximal DVT: anticoagulation (LMWH bridging to warfarin, or DOAC — rivaroxaban/apixaban). Duration: 3-6 months (provoked), indefinite (unprovoked/recurrent). IVC filter only if anticoagulation contraindicated. Thrombolysis for massive DVT with limb threat.",
     "近端DVT：抗凝治疗（LMWH过渡华法林或DOAC）。疗程3-6个月（诱因性）或无限期（无诱因/复发）。IVC滤器仅在抗凝禁忌时。溶栓仅用于威胁肢体。",
     "TVP proximal: anticoagulacion (HBPM o ACOD). Duracion 3-6 meses (provocada), indefinida (no provocada). Filtro VCI solo si contraindicada anticoagulacion."),
    ("A 50F has intermittent retrosternal burning chest pain relieved by antacids and worsened by lying down. EGD shows distal esophageal erosions. What is the most likely diagnosis?",
     ["GERD (erosive esophagitis)", "Eosinophilic esophagitis", "Infectious esophagitis (Candida)", "Achalasia", "Esophageal carcinoma"], 0,
     "GERD: retrosternal burning, acid regurgitation, worse supine/after meals, relieved by antacids. Erosive esophagitis on EGD. Treatment: PPI (omeprazole) for 8 weeks, lifestyle modifications (elevate head of bed, avoid meals before sleep, weight loss).",
     "GERD：胸骨后烧灼感，反酸，卧位/饭后加重。内镜下糜烂性食管炎。治疗：PPI 8周+生活方式改变。",
     "ERGE: ardor retroesternal, regurgitacion acida, empeora supino/post-comidas. Esofagitis erosiva en EGD. Tratamiento: IBP 8 sem + cambios estilo vida."),
    ("A 35M has chronic diarrhea, abdominal pain, weight loss, and perianal fistulas. Colonoscopy shows skip lesions, cobblestoning, and transmural inflammation. Diagnosis?",
     ["Crohn disease", "Ulcerative colitis", "Irritable bowel syndrome", "Celiac disease", "Infectious colitis"], 0,
     "Crohn: transmural, skip lesions, cobblestoning, any part of GI tract (mouth to anus), fistulas/strictures, perianal disease, granulomas on biopsy. UC: continuous from rectum proximally, mucosal only, bloody diarrhea. IBD treatment: steroids, biologics, immunomodulators.",
     "克罗恩病：全层性、节段性、鹅卵石样、可累及消化道任何部位、瘘管/狭窄、肛周病变、肉芽肿。UC：直肠起连续分布、仅黏膜、血性腹泻。",
     "Crohn: transmural, lesiones saltatorias, empedrado, cualquier parte TGI, fistulas, enfermedad perianal. CU: continua desde recto, solo mucosa, diarrea sanguinolenta."),
    ("A 55M with alcoholic cirrhosis develops confusion, asterixis, and fetor hepaticus. What precipitating factor should be investigated first?",
     ["GI bleeding, infection (SBP), or electrolyte disturbance", "Hepatocellular carcinoma", "Portal vein thrombosis", "Acute alcoholic hepatitis only", "Budd-Chiari syndrome"], 0,
     "Hepatic encephalopathy precipitating factors: GI bleeding, infection (SBP, UTI, pneumonia), electrolyte imbalance (hyponatremia, hypokalemia), constipation, sedatives, high protein intake. Treatment: lactulose (titrate to 2-3 soft stools/day) + rifaximin.",
     "肝性脑病诱因：消化道出血、感染、电解质紊乱、便秘、镇静剂、高蛋白饮食。治疗：乳果糖+利福昔明。",
     "Encefalopatia hepatica precipitantes: hemorragia GI, infeccion, alteracion electrolitos, estrenimiento, sedantes. Tratamiento: lactulosa + rifaximina."),
    ("A 45F on long-term NSAIDs for osteoarthritis develops iron deficiency anemia. What is the most likely source of blood loss?",
     ["GI bleeding (gastric/duodenal ulcers from NSAID enteropathy)", "Heavy menstrual bleeding", "Colon cancer", "Celiac disease", "Hemorrhoids"], 0,
     "NSAID-induced GI bleeding is common (gastric and duodenal ulcers, also small bowel). NSAIDs inhibit COX-1 → decreased prostaglandins → decreased mucosal protection. Add PPI for gastroprotection. Consider COX-2 selective NSAIDs (celecoxib) with caution (cardiovascular risk).",
     "NSAID引起的胃肠道出血是常见原因（胃十二指肠溃疡及小肠病变）。NSAIDs抑制COX-1→前列腺素减少→黏膜保护下降。加用PPI保护胃黏膜。",
     "AINE causan hemorragia GI por ulceras gastricas/duodenales. Inhiben COX-1 → menos prostaglandinas → menos proteccion mucosa. Agregar IBP."),
    ("A 65M has acute onset of severe flank pain radiating to the groin with hematuria. Non-contrast CT shows a 6 mm stone in the distal ureter. Management?",
     ["Medical expulsive therapy (tamsulosin) + pain control + hydration", "Immediate ureteroscopy", "Shockwave lithotripsy", "Percutaneous nephrolithotomy", "Observation only with follow-up in 4 weeks"], 0,
     "Distal ureteral stone <10 mm and no signs of infection/obstruction: trial of medical expulsive therapy (alpha-blocker like tamsulosin). Indications for intervention: >10 mm, refractory pain, infection, AKI, solitary kidney, stone not passing in 4-6 weeks.",
     "输尿管远端结石<10mm、无感染/梗阻征象：试行药物排石（坦索罗辛）。干预指征：>10mm、顽固疼痛、感染、AKI、孤立肾、4-6周未排出。",
     "Calculo distal <10mm sin infeccion/obstruccion: terapia expulsiva medica (tamsulosina). Intervencion: >10mm, dolor refractario, infeccion, IRA."),
    ("A 70M with BPH develops acute urinary retention. Bladder scan shows 900 mL. What is the first step in management?",
     ["Urethral catheterization to relieve obstruction", "Start tamsulosin immediately", "Immediate TURP (surgery)", "Suprapubic catheter only", "Observation with voiding trial"], 0,
     "Acute urinary retention: immediate catheterization to relieve obstruction and prevent renal damage. Then start alpha-blocker (tamsulosin) to attempt trial without catheter (TWOC) in 2-3 days. If TWOC fails: continue catheter + add 5-alpha reductase inhibitor, consider surgery.",
     "急性尿潴留：立即导尿解除梗阻。然后开始α受体阻滞剂，2-3天后试行拔管。拔管失败：继续导尿+5α还原酶抑制剂，考虑手术。",
     "RAO: cateterismo inmediato. Luego alfa-bloqueante, intentar retirada en 2-3 dias. Si falla: continuar sonda + 5-ARI, considerar cirugia."),
    ("A 60M hospitalized for pneumonia develops confusion, tremor, tachycardia, and visual hallucinations on day 3. He has a history of heavy alcohol use. What is the most likely diagnosis?",
     ["Alcohol withdrawal delirium (delirium tremens)", "Wernicke encephalopathy", "Hepatic encephalopathy", "ICU delirium", "Sepsis-associated encephalopathy"], 0,
     "Delirium tremens: onset 48-96 hours after last drink. Autonomic hyperactivity (tachycardia, HTN, diaphoresis) + hallucinations + confusion. Treatment: benzodiazepines (diazepam, lorazepam) — symptom-triggered or fixed-dose. Also give thiamine before glucose to prevent Wernicke.",
     "震颤谵妄：最后饮酒后48-96小时发作。自主神经亢进+幻觉+意识混乱。治疗：苯二氮卓类。葡萄糖前先补充硫胺素预防Wernicke脑病。",
     "Delirium tremens: 48-96h post-ultima bebida. Hiperactividad autonomica + alucinaciones + confusion. Tratamiento: benzodiacepinas. Tiamina antes de glucosa."),
    ("A 40F with SLE develops sudden onset pleuritic chest pain and dyspnea. CXR is normal, but CT angiography shows filling defects in segmental pulmonary arteries. What is the most likely cause of her hypercoagulable state?",
     ["Antiphospholipid syndrome (lupus anticoagulant)", "Factor V Leiden mutation", "Prothrombin gene mutation", "Protein C deficiency", "Antithrombin III deficiency"], 0,
     "SLE + thrombosis = antiphospholipid syndrome (APS). Lupus anticoagulant (prolonged aPTT, not corrected with mixing) and anti-cardiolipin/beta-2-glycoprotein antibodies. Treatment: lifelong anticoagulation with warfarin (target INR 2-3, or 3-4 if recurrent).",
     "SLE+血栓=抗磷脂综合征。狼疮抗凝物+抗心磷脂抗体。治疗：终身华法林抗凝（INR 2-3，复发者3-4）。",
     "LES + trombosis = SAF. Anticoagulante lupico + anticuerpos anticardiolipina. Tratamiento: anticoagulacion de por vida con warfarina."),
    ("A 55M has Stage III CKD (eGFR 45). Which medication class should be avoided or dose-adjusted?",
     ["Metformin, NSAIDs, and certain antibiotics (aminoglycosides, vancomycin)", "ACE inhibitors absolutely contraindicated", "Statins cannot be used", "Thiazides are preferred over loop diuretics", "All beta-blockers are contraindicated"], 0,
     "CKD: avoid NSAIDs (reduce renal blood flow), avoid metformin if eGFR <30 (lactic acidosis risk). Adjust antibiotic doses (aminoglycosides, vancomycin). ACEi/ARB are renoprotective in proteinuric CKD. Statins are indicated in CKD (ASCVD risk).",
     "CKD：避免NSAIDs、eGFR<30时避免二甲双胍。调整抗生素剂量。ACEi/ARB对蛋白尿性CKD有肾脏保护作用。他汀类药物在CKD中有指征。",
     "ERC: evitar AINEs, metformina si TFGe <30. Ajustar antibioticos. IECA/ARA-II renoprotectores. Estatinas indicadas en ERC."),
    ("A 60F with known diverticulosis develops LLQ abdominal pain, fever, and leukocytosis. CT shows colonic wall thickening and pericolic fat stranding. Diagnosis?",
     ["Acute diverticulitis", "Acute appendicitis", "Ischemic colitis", "Inflammatory bowel disease", "Colorectal cancer"], 0,
     "Diverticulitis: LLQ pain, fever, leukocytosis. CT confirms. Uncomplicated (no abscess, perforation): outpatient oral antibiotics (ciprofloxacin + metronidazole or amoxicillin-clavulanate) + clear liquids. Complicated: IV antibiotics, possible drainage/surgery.",
     "憩室炎：左下腹痛+发热+白细胞增多。CT确诊。非复杂性：口服抗生素+流质饮食。复杂性：IV抗生素、可能引流/手术。",
     "Diverticulitis: dolor FII, fiebre, leucocitosis. TAC confirma. No complicada: antibioticos orales + liquidos claros. Complicada: IV antibioticos, drenaje/cirugia."),
    ("A 70M with metastatic prostate cancer develops severe bone pain. Labs show calcium 12.5 mg/dL. What is the immediate management?",
     ["Aggressive IV normal saline + calcitonin + bisphosphonate (zoledronic acid)", "Oral calcium supplements", "Furosemide alone", "Prednisone alone", "Pamidronate only (works in 2-4 days)"], 0,
     "Hypercalcemia emergency: (1) aggressive IV NS (4-6L/day), (2) calcitonin (rapid but tachyphylaxis within 48h), (3) bisphosphonate (zoledronic acid or pamidronate) — takes 2-4 days for full effect. Avoid furosemide until euvolemic. Treat underlying cause.",
     "高钙血症急症：(1)积极静脉生理盐水，(2)降钙素（快速但48h内快速耐受），(3)双膦酸盐。避免血容量正常前使用呋塞米。",
     "Hipercalcemia emergencia: (1) SF IV agresiva, (2) calcitonina (rapida, taquifilaxia 48h), (3) bifosfonato. Evitar furosemida hasta euvolemia."),
    ("Which ECG changes are seen in hyperkalemia (progression from mild to severe)?",
     ["Peaked T waves → loss of P waves → wide QRS → sine wave → VF", "U waves → ST depression → prolonged QT", "Delta wave → short PR → wide QRS", "ST elevation → Q waves → T inversion", "Prolonged PR → Type 1 second-degree block → complete heart block"], 0,
     "Hyperkalemia ECG progression: peaked T (K >5.5), loss of P waves (K >6.5), wide QRS (K >7), sine wave pattern (K >8), VF/asystole. Emergency treatment: IV calcium gluconate (stabilizes cardiac membrane), insulin + glucose, bicarbonate, dialysis.",
     "高钾血症ECG进展：T波高尖→P波消失→QRS增宽→正弦波→室颤。紧急治疗：IV葡萄糖酸钙（稳定心肌细胞膜）+胰岛素+葡萄糖+碳酸氢钠+透析。",
     "Hiperkalemia ECG: T picuda → perdida P → QRS ancho → sinusoidal → FV. Tratamiento emergencia: gluconato calcio IV + insulina + glucosa + bicarbonato + dialisis."),
    ("A 65M with long-standing hypertension and diabetes has an episode of flash pulmonary edema. Renal angiogram is most likely to show?",
     ["Bilateral renal artery stenosis", "Renal artery aneurysm", "Renal vein thrombosis", "Atheroembolic renal disease", "Normal renal arteries"], 0,
     "Flash pulmonary edema + HTN + DM + CKD = consider bilateral renal artery stenosis. Renovascular HTN from atherosclerosis. ACEi/ARB can precipitate AKI in bilateral stenosis. Diagnose: renal artery duplex, CT/MR angiography. Treatment: medical + possible stenting.",
     "闪电式肺水肿+高血压+糖尿病+CKD→考虑双侧肾动脉狭窄。ACEi/ARB可诱发AKI。诊断：肾动脉彩超、CTA/MRA。治疗：药物+可能支架。",
     "Edema pulmonar subito + HTA + DM + ERC → estenosis bilateral arteria renal. IECA/ARA-II precipitan IRA. Dx: duplex, angio-TAC. Tratamiento: medico + stent."),
    ("A 55M with cirrhosis and ascites undergoes diagnostic paracentesis. Ascitic fluid shows PMN >250 cells/uL. What is the diagnosis?",
     ["Spontaneous bacterial peritonitis (SBP)", "Secondary bacterial peritonitis", "Malignant ascites", "Pancreatic ascites", "Chylous ascites"], 0,
     "SBP: ascitic PMN >250, positive culture (usually monomicrobial — E. coli, Klebsiella, Strep). Treatment: IV antibiotics (cefotaxime or ceftriaxone) + albumin (day 1: 1.5 g/kg, day 3: 1 g/kg) to prevent hepatorenal syndrome. SBP prophylaxis: norfloxacin or TMP-SMX.",
     "SBP：腹水PMN>250，培养阳性（通常单一菌）。治疗：IV抗生素+白蛋白预防肝肾综合征。SBP预防：诺氟沙星或TMP-SMX。",
     "PBE: PMN >250 en ascitis, cultivo positivo. Tratamiento: antibioticos IV + albumina. Profilaxis: norfloxacino o TMP-SMX."),
    ("A 45F on methimazole for Graves disease develops fever, severe sore throat, and agranulocytosis. What is the most appropriate management?",
     ["Stop methimazole, admit for broad-spectrum antibiotics, consider G-CSF", "Continue methimazole, add NSAIDs", "Increase methimazole dose", "Switch to propylthiouracil (PTU)", "Observation with outpatient follow-up"], 0,
     "Methimazole-induced agranulocytosis: stop drug immediately. Admit for fever workup, broad-spectrum antibiotics, and G-CSF. Do NOT switch to PTU (cross-reactivity). Definitive treatment: radioactive iodine or thyroidectomy. Risk highest in first months.",
     "甲巯咪唑引起的粒细胞缺乏：立即停药。住院、广谱抗生素、G-CSF。不要换用PTU（交叉反应）。根治：放射性碘或手术。",
     "Agranulocitosis por metimazol: suspender inmediatamente. Ingreso, ATB amplio espectro, G-CSF. NO cambiar a PTU. Definitivo: yodo radiactivo o cirugia."),
    ("A 35M has recurrent episodes of severe hypertension, headache, palpitations, and diaphoresis. 24-hour urine metanephrines are elevated. What is the most likely diagnosis?",
     ["Pheochromocytoma", "Primary hyperaldosteronism (Conn syndrome)", "Cushing syndrome", "Renovascular hypertension", "Essential hypertension"], 0,
     "Pheochromocytoma: catecholamine-secreting adrenal tumor. Triad: episodic headache + palpitations + diaphoresis + severe HTN. Diagnose: plasma free metanephrines or 24-hour urine metanephrines. Treatment: alpha-blockade (phenoxybenzamine) BEFORE beta-blockade to avoid unopposed alpha stimulation.",
     "嗜铬细胞瘤：儿茶酚胺分泌性肾上腺肿瘤。三联征：阵发性头痛+心悸+出汗+严重高血压。诊断：血浆游离甲氧基肾上腺素或24小时尿。治疗：先用α阻滞剂再用β阻滞剂。",
     "Feocromocitoma: tumor suprarrenal secretor catecolaminas. Triada: cefalea episodica + palpitaciones + diaforesis. Dx: metanefrinas. Tx: alfa-bloqueo ANTES de beta-bloqueo."),
    ("A 50M with alcoholic liver disease has ascites. Serum sodium is 128 mEq/L. What is the most appropriate fluid and sodium management?",
     ["Fluid restriction (1-1.5 L/day) — avoid rapid Na correction", "Normal saline bolus", "3% hypertonic saline", "Liberal fluids to improve renal perfusion", "Salt tablets"], 0,
     "Cirrhosis with dilutional hyponatremia (hypervolemic): fluid restriction 1-1.5L/day. Avoid rapid Na correction (risk of central pontine myelinolysis). Vaptans (tolvaptan) can be used short-term. Do not give normal saline (worsens ascites/edema).",
     "肝硬化稀释性低钠：限液1-1.5L/天。避免快速纠正血钠（中央脑桥髓鞘溶解风险）。不要补充生理盐水。",
     "Cirrosis con hiponatremia dilucional: restriccion liquidos 1-1.5L/dia. Evitar correccion rapida Na. No dar SF."),
    ("A 55F with breast cancer on chemotherapy (doxorubicin) develops progressive dyspnea, orthopnea, and bilateral pulmonary edema on CXR. Echo shows diffuse hypokinesis and LVEF 25%. What is the most likely cause?",
     ["Doxorubicin-induced cardiomyopathy", "Ischemic cardiomyopathy", "Stress (Takotsubo) cardiomyopathy", "Pericardial effusion with tamponade", "Myocarditis"], 0,
     "Doxorubicin: dose-dependent cardiotoxicity (cumulative >450 mg/m2). Direct myocyte damage → dilated cardiomyopathy. Prevent: dexrazoxane, liposomal formulation. Monitor: serial echo/MUGA. Treat: standard HF therapy (ACEi, beta-blockers).",
     "阿霉素剂量依赖性心脏毒性（累积>450 mg/m2）。直接心肌细胞损伤→扩张型心肌病。预防：右雷佐生、脂质体制剂。治疗：标准心衰治疗。",
     "Doxorrubicina: cardiotoxicidad dependiente dosis (>450 mg/m2 acumulada). DanO miocitico directo → miocardiopatia dilatada. Prevencion: dexrazoxano."),
    ("A 60M has worsening dyspnea on exertion, JVD, hepatomegaly, and ascites. Echo shows preserved LVEF but severe TR. What type of heart failure?",
     ["Right-sided heart failure", "HFrEF (HF with reduced EF)", "HFpEF (HF with preserved EF)", "High-output heart failure", "Biventricular failure"], 0,
     "Right HF: JVD, hepatomegaly, ascites, peripheral edema. Causes: left HF (most common), pulmonary hypertension, TR, RV infarction. Echo shows preserved LVEF but RV dysfunction. Treatment: diuretics, treat underlying cause.",
     "右心衰：JVD、肝大、腹水、外周水肿。病因：左心衰（最常见）、肺高压、TR、右室心梗。治疗：利尿剂+治疗基础病因。",
     "IC derecha: IY, hepatomegalia, ascitis, edema periferico. Causas: IC izquierda, HTP, IT, IAM VD. Tratamiento: diureticos + tratar causa."),
    ("A 28F with SLE develops facial and lower extremity edema, foamy urine, and proteinuria of 4.5 g/day. Renal biopsy shows thickened GBM with subepithelial deposits ('spike and dome'). What class of lupus nephritis?",
     ["Class V — Membranous lupus nephritis", "Class IV — Diffuse proliferative", "Class III — Focal proliferative", "Class II — Mesangial proliferative", "Class I — Minimal mesangial"], 0,
     "Lupus nephritis Class V: membranous — subepithelial deposits with 'spike and dome' on silver stain, nephrotic-range proteinuria. Treat with steroids + immunosuppression (MMF or cyclophosphamide). Class IV is the most common and most severe (diffuse proliferative).",
     "狼疮肾炎V型：膜性——上皮下沉积，银染"钉突和穹顶"，肾病范围蛋白尿。IV型最常见最严重（弥漫增生性）。",
     "Nefritis lupica Clase V: membranosa — depositos subepiteliales, proteinuria nefrotica. Tratar: esteroides + inmunosupresion. Clase IV mas comun y severa."),
    ("A 65F on chronic NSAIDs develops acute kidney injury. BUN/Cr ratio is <15:1, FeNa >2%, and urine sediment shows muddy brown casts. What is the cause of AKI?",
     ["Acute tubular necrosis (ATN)", "Prerenal azotemia", "Acute interstitial nephritis", "Post-renal obstruction", "Glomerulonephritis"], 0,
     "ATN: FeNa >2%, muddy brown casts, BUN/Cr <15:1, urine Na >40. Causes: ischemia (shock, sepsis), nephrotoxins (NSAIDs, aminoglycosides, contrast). Prerenal: FeNa <1%, BUN/Cr >20:1. AIN (NSAIDs, antibiotics): WBC casts, eosinophiluria, eosinophilia.",
     "ATN：FeNa>2%，泥褐色管型，BUN/Cr<15:1。病因：缺血、肾毒性药物。肾前性：FeNa<1%，BUN/Cr>20:1。AIN：白细胞管型、嗜酸性粒细胞尿。",
     "NTA: FeNa >2%, cilindros marrones, BUN/Cr <15:1. Causas: isquemia, nefrotoxicos. Prerrenal: FeNa <1%, BUN/Cr >20:1. NIA: cilindros leucocitarios."),
    ("A 50M with diabetes has non-healing foot ulcer with surrounding erythema and exposed bone. What is the most important next step?",
     ["Probe-to-bone test + X-ray to evaluate for osteomyelitis", "Topical antibiotics", "Wound culture only", "Amputation without imaging", "Compression therapy"], 0,
     "Diabetic foot ulcer with suspected osteomyelitis: probe-to-bone test (positive if bone palpable), X-ray (changes take 2 weeks), MRI if unclear. Broad-spectrum antibiotics + surgical debridement. Offloading, glycemic control, vascular assessment.",
     "糖尿病足溃疡怀疑骨髓炎：探骨试验+X线。广谱抗生素+外科清创。减压+血糖控制+血管评估。",
     "Ulcera pie diabetico sospecha osteomielitis: prueba sonda-hueso + radiografia. ATB amplio espectro + desbridamiento. Descarga + control glucemico."),
    ("Which patient should be screened for abdominal aortic aneurysm (AAA) according to USPSTF guidelines?",
     ["65-75M with smoking history — one-time ultrasound", "All adults >50 — annual ultrasound", "Women >65 regardless of smoking status", "All patients with hypertension", "Only symptomatic patients"], 0,
     "AAA screening: one-time abdominal ultrasound for men 65-75 who have ever smoked. Selective screening for men 65-75 who have never smoked. Not routinely recommended for women. AAA >5.5 cm or rapidly expanding: elective repair.",
     "AAA筛查：65-75岁曾吸烟男性一次性腹部超声。>5.5cm或快速增长择期修复。",
     "Cribado AAA: ecografia abdominal unica en hombres 65-75 con historia tabaquismo. >5.5 cm o expansion rapida: reparacion electiva."),
    ("A 70F nursing home resident develops confusion, fever, and cough with purulent sputum. CXR shows right lower lobe consolidation. What empiric antibiotics should be started considering healthcare-associated pneumonia risk?",
     ["Anti-pseudomonal beta-lactam + anti-MRSA coverage (vancomycin)", "Amoxicillin alone", "Azithromycin monotherapy", "Doxycycline monotherapy", "Trimethoprim-sulfamethoxazole alone"], 0,
     "Healthcare-associated pneumonia (HCAP): MDR organisms including Pseudomonas, MRSA. Empiric: anti-pseudomonal beta-lactam (cefepime, piperacillin-tazobactam, meropenem) + vancomycin or linezolid. CAP (community): ceftriaxone + azithromycin.",
     "医疗相关肺炎：MDR病原体包括铜绿假单胞菌、MRSA。经验治疗：抗假单胞菌β-内酰胺+万古霉素或利奈唑胺。",
     "Neumonia asociada cuidados salud: MDR incluyendo Pseudomonas, MRSA. Empirico: betalactamico antipseudomonas + vancomicina."),
    ("A 55M with HIV (CD4 120, not on ART) develops progressive dyspnea, dry cough, and hypoxia with ground-glass opacities on CT. Induced sputum shows Pneumocystis jirovecii. What is the preferred treatment?",
     ["Trimethoprim-sulfamethoxazole (TMP-SMX) — high dose", "Clindamycin + primaquine", "Pentamidine IV", "Atovaquone", "Fluconazole"], 0,
     "PCP treatment: high-dose TMP-SMX (15-20 mg/kg/day TMP) for 21 days. If PaO2 <70 or A-a gradient >35: add corticosteroids (prednisone) within 72h. Prophylaxis: TMP-SMX when CD4 <200. Alternatives: pentamidine, atovaquone, dapsone + TMP.",
     "PCP治疗：大剂量TMP-SMX 21天。如PaO2<70或A-a梯度>35：加用糖皮质激素。预防：CD4<200时TMP-SMX。",
     "Tratamiento PCP: TMP-SMX dosis alta 21 dias. Si PaO2 <70: agregar corticoides. Profilaxis: CD4 <200."),
    ("A 60M has monoclonal gammopathy of undetermined significance (MGUS). What is the annual risk of progression to multiple myeloma?",
     ["1% per year", "10% per year", "25% per year", "50% per year", "Nearly 100% progression rate"], 0,
     "MGUS: M-protein <3 g/dL, bone marrow plasma cells <10%, no CRAB criteria. Annual progression risk ~1%. Monitor with SPEP and clinical follow-up. Smoldering myeloma: M-protein >=3 or plasma cells 10-60%, no CRAB, 10%/year progression risk.",
     "MGUS：M蛋白<3g/dL，骨髓浆细胞<10%，无CRAB标准。每年进展风险约1%。随访SPEP。冒烟型骨髓瘤：进展风险10%/年。",
     "MGUS: proteina M <3 g/dL, celulas plasmaticas MO <10%, sin CRAB. Riesgo progresion ~1%/ano. Monitorizar SPEP."),
    ("A 45F has acute pancreatitis with epigastric pain radiating to back, elevated lipase (3x ULN), and CT showing peripancreatic fluid. What is the most important early management?",
     ["Aggressive IV fluid resuscitation with lactated Ringer", "Immediate ERCP", "Prophylactic antibiotics", "NPO for 7 days minimum", "Surgical debridement within 24h"], 0,
     "Acute pancreatitis: aggressive IV fluid resuscitation (LR preferred over NS) — most critical early step. Pain control. NPO initially, advance diet as tolerated. Antibiotics only if infected necrosis suspected. ERCP within 24h for gallstone pancreatitis with cholangitis.",
     "急性胰腺炎：积极静脉液体复苏（首选乳酸林格液）——最关键早期步骤。NPO初始，逐步恢复饮食。仅怀疑感染坏死时用抗生素。",
     "Pancreatitis aguda: reanimacion IV agresiva (RL preferido) — paso temprano mas critico. Ayuno inicial, avanzar dieta tolerada. ATB solo necrosis infectada."),
    ("A 75F with atrial fibrillation (CHADS2Vasc 5) is started on warfarin. What is the target INR?",
     ["2.0-3.0 for most indications including AF", "1.5-2.0", "2.5-3.5", "3.0-4.0", "1.0-1.5"], 0,
     "Warfarin target INR: 2.0-3.0 for AF, DVT/PE treatment, most indications. INR 2.5-3.5 for mechanical mitral valve. CHADS2Vasc: CHF(1), HTN(1), Age>=75(2), DM(1), Stroke/TIA(2), Vascular(1), Age 65-74(1), Sex female(1). Score >=2: anticoagulation.",
     "华法林目标INR：房颤、DVT/PE治疗为2.0-3.0。机械二尖瓣2.5-3.5。CHADS2Vasc评分>=2需抗凝。",
     "INR objetivo warfarina: 2.0-3.0 para FA, TVP/TEP. Valvula mitral mecanica: 2.5-3.5. CHADS2Vasc >=2: anticoagular."),
    ("A 50M with chronic hepatitis B has HBeAg+, HBV DNA >20,000 IU/mL, and ALT 2x ULN. What is the preferred first-line treatment?",
     ["Tenofovir or entecavir (nucleos(t)ide analogs)", "Interferon-alpha", "Lamivudine monotherapy", "Adefovir", "Observation without treatment"], 0,
     "Chronic HBV treatment indications: HBeAg+ with HBV DNA >20,000 and ALT >2x ULN; or cirrhosis with detectable HBV DNA; or HBeAg- with HBV DNA >2,000 and ALT elevated. First-line: tenofovir (TDF or TAF) or entecavir. Avoid lamivudine (resistance).",
     "慢性乙肝治疗指征：HBeAg+伴HBV DNA>20,000和ALT>2倍正常上限。一线：替诺福韦或恩替卡韦。避免拉米夫定（耐药）。",
     "Tratamiento hepatitis B cronica: HBeAg+ con ADN VHB >20000 y ALT >2x. Primera linea: tenofovir o entecavir. Evitar lamivudina."),
    ("A 45F with rheumatoid arthritis on methotrexate develops dry cough, fever, and bilateral interstitial infiltrates on CXR. What is the most likely diagnosis?",
     ["Methotrexate-induced pneumonitis", "Rheumatoid arthritis-associated ILD", "Community-acquired pneumonia", "Pulmonary embolism", "Tuberculosis reactivation"], 0,
     "Methotrexate pneumonitis: subacute cough, fever, dyspnea, bilateral infiltrates. Can occur at any time during treatment. Treatment: stop MTX, supportive care, consider corticosteroids. RA-ILD is chronic progressive (UIP pattern).",
     "甲氨蝶呤肺炎：亚急性咳嗽、发热、呼吸困难、双侧浸润。治疗：停用MTX、支持治疗、考虑激素。RA-ILD为慢性进行性。",
     "Neumonitis por metotrexato: tos subaguda, fiebre, disnea, infiltrados bilaterales. Tx: suspender MTX, soporte, corticoides."),
    ("A 35M on peritoneal dialysis develops cloudy dialysate effluent, abdominal pain, and fever. Dialysate WBC >100 with >50% neutrophils. What is the management?",
     ["Intraperitoneal antibiotics (vancomycin + ceftazidime or aminoglycoside)", "Immediate catheter removal", "Switch to hemodialysis permanently", "Oral antibiotics only", "Wait for culture results before treatment"], 0,
     "PD peritonitis: IP antibiotics (vancomycin + gram-negative coverage) after obtaining cultures. Catheter removal if: fungal, refractory, relapsing, or tunnel infection. Empiric treatment based on local antibiogram, do not wait for culture results.",
     "腹膜透析腹膜炎：腹腔内抗生素（万古霉素+抗革兰阴性菌）。真菌性、难治性、复发性或隧道感染时拔管。",
     "Peritonitis DP: antibioticos intraperitoneales. Retirada cateter si: fungica, refractaria, recurrente, infeccion tunel."),
    ("A 65M with COPD develops worsening dyspnea, increased sputum purulence and volume. What defines this as COPD exacerbation?",
     ["Acute worsening of respiratory symptoms beyond normal day-to-day variation, requiring change in therapy", "Any productive cough", "FEV1 decrease of 10%", "Any emergency department visit", "Oxygen saturation <88% at rest"], 0,
     "COPD exacerbation: acute worsening of dyspnea, cough, and/or sputum (increased volume or purulence) beyond normal variation, requiring change in treatment. Treat with bronchodilators (SABA + SAMA), systemic steroids, antibiotics if purulent sputum.",
     "COPD加重：急性呼吸困难、咳嗽、咳痰加重，需改变治疗方案。治疗：SABA+SAMA、全身激素、如脓痰则用抗生素。",
     "Exacerbacion EPOC: empeoramiento agudo disnea, tos, esputo, requiere cambio tratamiento. Tx: SABA+SAMA, corticoides sistemicos, ATB si esputo purulento."),
    ("A 55F with ulcerative colitis for 20 years. What is the recommended surveillance for colorectal cancer?",
     ["Colonoscopy every 1-2 years with random biopsies starting 8 years after diagnosis", "Colonoscopy every 5 years", "Annual fecal occult blood test", "Flexible sigmoidoscopy every 3 years", "CT colonography every 5 years"], 0,
     "UC/Crohn colitis: CRC surveillance colonoscopy every 1-2 years starting 8 years after diagnosis with random biopsies (at least 32 biopsies). Chromoendoscopy preferred. Colectomy if high-grade dysplasia or CRC found.",
     "UC/Crohn结肠炎：诊断8年后每1-2年结肠镜筛查+随机活检（至少32块）。发现高度异型增生或CRC时行结肠切除术。",
     "CU/Crohn colitis: colonoscopia cribado cada 1-2 anos desde 8 anos post-diagnostico con biopsias aleatorias. Colectomia si displasia alto grado."),
    ("A 70M with GERD and Barrett esophagus has low-grade dysplasia on surveillance endoscopy. What is the next step?",
     ["Repeat EGD in 6 months with aggressive PPI therapy, or endoscopic ablation", "Immediate esophagectomy", "No further surveillance needed", "Annual endoscopy is sufficient", "Chest CT for staging"], 0,
     "Barrett with low-grade dysplasia: increased PPI + repeat EGD in 6 months. Consider endoscopic eradication (radiofrequency ablation). High-grade dysplasia: endoscopic resection/ablation. No dysplasia: EGD every 3-5 years with biopsies.",
     "Barrett伴低度异型增生：强化PPI+6个月复查EGD。考虑内镜下消融。高度异型增生：内镜下切除/消融。无异型增生：每3-5年EGD。",
     "Barrett con displasia bajo grado: aumentar IBP + repetir EGD 6 meses + considerar ablacion. Alto grado: reseccion/ablacion endoscopica."),
    ("A 60M has severe sepsis with hypotension refractory to 30 mL/kg IV fluids. What is the next vasopressor of choice?",
     ["Norepinephrine — first-line vasopressor in septic shock", "Dopamine", "Epinephrine", "Vasopressin", "Phenylephrine"], 0,
     "Septic shock: norepinephrine first-line. Add vasopressin (0.03 U/min) as second agent, not titrated. Epinephrine added if refractory. Dopamine no longer recommended. Target MAP >=65 mmHg. Early antibiotics (within 1 hour) and source control are critical.",
     "感染性休克：去甲肾上腺素首选。加用加压素作为二线。目标MAP>=65 mmHg。1小时内使用抗生素和感染源控制至关重要。",
     "Shock septico: norepinefrina primera linea. Agregar vasopresina segunda linea. Objetivo PAM >=65 mmHg. ATB <1h y control foco."),
    ("A 45M with known sarcoidosis has bilateral hilar lymphadenopathy and erythema nodosum on presentation. What is this constellation called?",
     ["Lofgren syndrome", "Heerfordt syndrome (uveoparotid fever)", "Mikulicz syndrome", "Blau syndrome", "Löfgren is not a recognized syndrome"], 0,
     "Lofgren syndrome: bilateral hilar adenopathy + erythema nodosum + arthralgias/arthritis (often ankles). Good prognosis — often self-limited. Heerfordt: uveitis + parotid enlargement + facial nerve palsy + fever. Sarcoidosis: non-caseating granulomas.",
     "Lofgren综合征：双侧肺门淋巴结肿大+结节性红斑+关节痛。预后良好。Heerfordt：葡萄膜炎+腮腺肿大+面神经麻痹+发热。结节病：非干酪性肉芽肿。",
     "Sindrome Lofgren: adenopatia hiliar bilateral + eritema nodoso + artralgias. Buen pronostico. Heerfordt: uveitis + parotida + paralisis facial."),
    ("A 60F with polymyalgia rheumatica is started on prednisone 15 mg/day. What is the most important complication to monitor for, and what prophylactic measure should be considered?",
     ["Osteoporosis — calcium + vitamin D, consider bisphosphonate. Also monitor for giant cell arteritis symptoms.", "Peptic ulcer — routine PPI for all patients", "Diabetes — routine insulin", "Cataracts — annual eye exam only", "Avascular necrosis — routine MRI screening"], 0,
     "PMR: low-dose prednisone (10-20 mg/day) with dramatic response. Monitor for GCA (headache, jaw claudication, vision changes — urgent!). Osteoporosis prevention: calcium + vitamin D, bisphosphonate if high risk. Taper steroids slowly over months.",
     "PMR：低剂量泼尼松，效果显著。监测GCA。骨质疏松预防：钙+维生素D，高风险者加双膦酸盐。激素缓慢减量。",
     "PMR: prednisona dosis baja, respuesta dramatica. Vigilar ACG. Prevencion osteoporosis: calcio + vitamina D + bifosfonato. Reducir esteroides lentamente."),
    ("A 70M develops sudden onset of severe joint pain, swelling, and erythema in the first metatarsophalangeal joint. Arthrocentesis shows negatively birefringent needle-shaped crystals. What is the diagnosis?",
     ["Gout (monosodium urate crystals)", "Pseudogout (calcium pyrophosphate)", "Septic arthritis", "Rheumatoid arthritis", "Osteoarthritis"], 0,
     "Gout: negatively birefringent needle-shaped monosodium urate crystals. Pseudogout: positively birefringent rhomboid CPPD crystals. Septic arthritis: gram stain/culture positive, WBC usually >50K (>90% PMNs). Always rule out infection if monoarthritis.",
     "痛风：负性双折射针状尿酸单钠结晶。假性痛风：正性双折射菱形CPPD结晶。单关节炎必须排除感染。",
     "Gota: cristales urato monosodico aguja, birrefringencia negativa. Pseudogota: CPPD romboidal, birrefringencia positiva. Descartar infeccion en monoartritis."),
    ("A 55M develops involuntary, irregular, non-repetitive movements of the limbs and face 2 weeks after starting levodopa for Parkinson disease. What is this called?",
     ["Levodopa-induced dyskinesia", "Huntington disease chorea", "Tardive dyskinesia", "Essential tremor", "Myoclonus"], 0,
     "Levodopa-induced dyskinesia: peak-dose dyskinesia (choreiform movements at peak drug levels). Management: reduce individual levodopa dose (increase frequency), add amantadine, consider DBS. Tardive dyskinesia from antipsychotics involves oro-buccal-lingual movements.",
     "左旋多巴诱导的异动症：峰值剂量异动症。处理：减少单次剂量增加频次、加用金刚烷胺、考虑DBS。迟发性运动障碍为口-颊-舌运动。",
     "Discinesia por levodopa: movimientos coreiformes en pico de dosis. Manejo: reducir dosis individual, amantadina, considerar ECP."),
]

for qq in im_qs_step2:
    q(next_id, 'step2', 'Internal Medicine', *qq); next_id += 1

print(f"Batch 2 generated {len(lines)} questions (IDs {START_ID}-{next_id-1})")
sys.stdout.write("\n".join(lines))
