#!/usr/bin/env python3
"""
Generate 500 additional USMLE practice questions for the question bank.
Outputs TypeScript-compatible Question objects to append to questions.ts.
"""
import json, sys

# Start ID after the last existing question (last was 928)
START_ID = 929

questions = []

def q(id_num, step, subject, question_text, options, correct, en, zh, es, diff="Medium", hy_tag=None):
    """Add a question with all required fields"""
    obj = {
        "id": id_num,
        "step": step,
        "subject": subject,
        "question": question_text,
        "options": options,
        "correctAnswer": correct,
        "explanationEn": en,
        "explanationZh": zh,
        "explanationEs": es,
        "aiGenerated": True,
        "difficulty": diff,
    }
    if hy_tag:
        obj["highYieldTag"] = hy_tag
    questions.append(obj)

def to_ts():
    """Output as TypeScript array elements"""
    lines = []
    for q in questions:
        lines.append("  {")
        lines.append(f"    id: {q['id']}, step: '{q['step']}', subject: '{q['subject']}',")
        # Escape single quotes in question text
        qt = q['question'].replace("'", "\\'").replace("\n", " ")
        lines.append(f"    question: '{qt}',")
        opts = ", ".join(f"'{o.replace(chr(39), chr(92)+chr(39))}'" for o in q['options'])
        lines.append(f"    options: [{opts}],")
        lines.append(f"    correctAnswer: {q['correctAnswer']},")
        en = q['explanationEn'].replace("'", "\\'")
        zh = q['explanationZh'].replace("'", "\\'")
        es = q['explanationEs'].replace("'", "\\'")
        lines.append(f"    explanationEn: '{en}',")
        lines.append(f"    explanationZh: '{zh}',")
        lines.append(f"    explanationEs: '{es}',")
        lines.append(f"    aiGenerated: true,")
        lines.append(f"    difficulty: '{q['difficulty']}',")
        if q.get('highYieldTag'):
            lines.append(f"    highYieldTag: '{q['highYieldTag']}',")
        lines.append("  },")
    return "\n".join(lines)

# ===========================================================
# STEP 1 — 150 New Questions (IDs 929–1078)
# ===========================================================

next_id = START_ID

# --- Pathology (20 questions) ---
path_qs_step1 = [
    ("A 48M with chronic hepatitis C develops a 2 cm liver mass. Biopsy shows trabecular pattern of atypical hepatocytes. AFP is 450 ng/mL. What is the most likely precursor lesion?",
     ["Liver cell dysplasia", "Regenerative nodule", "Hepatic adenoma", "Focal nodular hyperplasia", "Biliary hamartoma"], 0,
     "Chronic hepatitis C → cirrhosis → dysplastic nodules → HCC. Liver cell dysplasia is the direct precursor lesion. AFP elevation confirms HCC diagnosis.",
     "慢性丙肝→肝硬化→异型增生结节→HCC。肝细胞异型增生是直接的前驱病变。AFP升高确认HCC诊断。",
     "Hepatitis C cronica → cirrosis → nodulos displasicos → HCC. Displasia hepatocelular es la lesion precursora directa."),
    ("Which receptor does VEGF primarily bind to promote tumor angiogenesis?",
     ["VEGFR-2 (KDR/Flk-1)", "EGFR (HER1)", "PDGFR-beta", "FGFR-1", "c-MET"], 0,
     "VEGF primarily signals through VEGFR-2 (KDR) to promote endothelial cell proliferation, migration, and angiogenesis. Anti-VEGF drugs (bevacizumab) and VEGFR TKIs target this pathway.",
     "VEGF主要通过VEGFR-2信号促进内皮细胞增殖、迁移和血管生成。抗VEGF药物（贝伐珠单抗）和VEGFR-TKIs靶向此通路。",
     "VEGF senala a traves de VEGFR-2 para promover proliferacion, migracion y angiogenesis de celulas endoteliales."),
    ("Which tumor suppressor gene is most commonly mutated in pancreatic adenocarcinoma?",
     ["TP53", "KRAS", "CDKN2A (p16)", "SMAD4 (DPC4)", "BRCA2"], 2,
     "Pancreatic adenocarcinoma progression: KRAS (early, >90%), then CDKN2A/p16 loss, then TP53 and SMAD4 (late). CDKN2A/p16 is the most commonly inactivated tumor suppressor gene in pancreatic cancer.",
     "胰腺癌进展：KRAS（早期，>90%），然后CDKN2A/p16失活，然后是TP53和SMAD4（晚期）。CDKN2A/p16是最常失活的肿瘤抑制基因。",
     "Progresion de adenocarcinoma pancreatico: KRAS, luego CDKN2A/p16, luego TP53 y SMAD4."),
    ("A 60F with long-standing rheumatoid arthritis develops splenomegaly and neutropenia. What is this condition called?",
     ["Felty syndrome", "Still disease", "Sjogren syndrome", "CREST syndrome", "Reiter syndrome"], 0,
     "Felty syndrome = RA + splenomegaly + neutropenia. Associated with severe, long-standing RA. Increased risk of infections due to neutropenia. Treatment: DMARDs, G-CSF, splenectomy if severe.",
     "Felty综合征 = RA + 脾肿大 + 中性粒细胞减少。与严重、长期的RA相关。中性粒细胞减少增加了感染风险。治疗：DMARDs、G-CSF、重症可行脾切除。",
     "Sindrome de Felty = AR + esplenomegalia + neutropenia. Aumenta riesgo de infecciones."),
    ("Which type of necrosis is characteristic of pancreatic fat necrosis?",
     ["Enzymatic fat necrosis with saponification", "Coagulative necrosis", "Liquefactive necrosis", "Caseous necrosis", "Fibrinoid necrosis"], 0,
     "Pancreatic enzymes (lipase) released during pancreatitis digest fat, releasing fatty acids that bind calcium → saponification (soap formation). Grossly appears as chalky white deposits.",
     "急性胰腺炎释放的脂肪酶消化脂肪，释放脂肪酸与钙结合→皂化作用。大体上表现为白垩样沉积。",
     "Lipasa pancreatica libera acidos grasos que se unen al calcio → saponificacion. Apariencia blanca yesosa."),
    ("Which cardiac marker rises first after myocardial infarction?",
     ["Myoglobin", "Troponin I", "CK-MB", "LDH", "AST"], 0,
     "Myoglobin rises within 1-4 hours (earliest). Troponin I/T rises at 4-6 hours and is most specific. CK-MB rises at 4-6 hours. LDH rises late (24-72h).",
     "肌红蛋白在1-4小时内升高（最早）。肌钙蛋白I/T在4-6小时升高，最具特异性。CK-MB在4-6小时升高。LDH升高较晚（24-72小时）。",
     "Mioglobina aumenta en 1-4h (mas temprano). Troponina I/T a las 4-6h, mas especifica. CK-MB a las 4-6h."),
    ("A tumor shows cells with 'signet ring' morphology. Mucicarmine stain is positive. What is the most common primary site?",
     ["Stomach", "Colon", "Breast", "Lung", "Pancreas"], 0,
     "Signet ring cell carcinoma most commonly arises in the stomach (diffuse-type gastric adenocarcinoma). Poor prognosis, tends to spread along peritoneal surfaces (linitis plastica).",
     "印戒细胞癌最常见于胃（弥漫型胃腺癌）。预后差，倾向于沿腹膜表面扩散（皮革胃）。",
     "Carcinoma de celulas en anillo de sello: mas comun en estomago (adenocarcinoma difuso). Mal pronostico, diseminacion peritoneal."),
    ("C-ANCA (anti-PR3) is most associated with which vasculitis?",
     ["Granulomatosis with polyangiitis (Wegener)", "Microscopic polyangiitis", "Eosinophilic granulomatosis with polyangiitis (Churg-Strauss)", "Polyarteritis nodosa", "IgA vasculitis (Henoch-Schonlein)"], 0,
     "c-ANCA (anti-PR3) = GPA/Wegener (lungs + kidneys + upper airway). p-ANCA (anti-MPO) = microscopic polyangiitis, Churg-Strauss. Both cause pauci-immune glomerulonephritis.",
     "c-ANCA（抗PR3）= GPA/韦格纳肉芽肿（肺+肾+上气道）。p-ANCA（抗MPO）= 显微镜下多血管炎、Churg-Strauss。两者均引起寡免疫复合物肾小球肾炎。",
     "c-ANCA (anti-PR3) = GPA/Wegener. p-ANCA (anti-MPO) = poliangeitis microscopica, Churg-Strauss."),
    ("What is the most common cause of nephrotic syndrome in adults?",
     ["Focal segmental glomerulosclerosis (FSGS)", "Membranous nephropathy", "Minimal change disease", "Membranoproliferative GN", "Diabetic nephropathy"], 1,
     "Membranous nephropathy is the most common primary cause of nephrotic syndrome in Caucasian adults. FSGS is most common in African Americans. Minimal change disease is most common in children.",
     "膜性肾病是高加索裔成人肾病综合征最常见的原发病因。FSGS在非裔美国人中最常见。微小病变病在儿童中最常见。",
     "Nefropatia membranosa: causa primaria mas comun de sindrome nefrotico en adultos caucasicos. FSGS en afroamericanos."),
    ("A liver biopsy shows 'piecemeal necrosis' at the limiting plate. What condition is this characteristic of?",
     ["Chronic active hepatitis", "Acute hepatitis A", "Alcoholic hepatitis", "Primary biliary cirrhosis", "Hemochromatosis"], 0,
     "Piecemeal necrosis (interface hepatitis) is characteristic of chronic active hepatitis (autoimmune or viral). The limiting plate between portal tracts and parenchyma is eroded by inflammatory cells.",
     "碎片样坏死（界面性肝炎）是慢性活动性肝炎的特征（自身免疫性或病毒性）。门管区与实质间的界板被炎症细胞侵蚀。",
     "Necrosis en sacabocados (hepatitis de interfase): caracteristica de hepatitis cronica activa. Limite entre espacio porta y parenquima erosionado."),
    ("Which oncogene is activated by t(8;14) translocation in Burkitt lymphoma?",
     ["c-MYC", "BCL-2", "BCL-6", "CCND1 (Cyclin D1)", "ALK"], 0,
     "t(8;14) places c-MYC (chr 8) next to IgH enhancer (chr 14) → c-MYC overexpression → Burkitt lymphoma. Starry-sky appearance on histology. Associated with EBV in endemic form.",
     "t(8;14)使c-MYC转移到IgH增强子旁→c-MYC过表达→伯基特淋巴瘤。组织学呈星空样表现。地方型与EBV相关。",
     "t(8;14) coloca c-MYC junto al potenciador IgH → sobreexpresion de c-MYC → linfoma de Burkitt. Aspecto de cielo estrellado."),
    ("PSA screening for prostate cancer primarily detects which zone of the prostate?",
     ["Peripheral zone", "Central zone", "Transition zone", "Periurethral zone", "Anterior zone"], 0,
     "Most prostate cancers (70%) arise in the peripheral zone — palpable on DRE. BPH arises in the transition zone. PSA + DRE are screening tools for peripheral zone cancers.",
     "大多数前列腺癌（70%）发生在外周带——DRE可触及。BPH发生在移行带。PSA + DRE用于外周带癌症的筛查。",
     "70% canceres de prostata surgen en zona periferica (palpable en DRE). HBP surge en zona de transicion."),
    ("What is the primary mechanism of prion disease (e.g., Creutzfeldt-Jakob disease)?",
     ["Conversion of PrPc to PrPSc (beta-sheet conformation)", "DNA viral integration", "RNA viral replication", "Bacterial endotoxin", "Fungal toxin production"], 0,
     "Prion diseases involve conversion of normal cellular prion protein (PrPc, alpha-helical) to pathologic scrapie form (PrPSc, beta-sheet rich). PrPSc acts as template to convert more PrPc. Spongiform degeneration on histology.",
     "朊病毒病涉及正常细胞朊蛋白（PrPc，α螺旋）转化为病理刮型（PrPSc，富含β折叠）。PrPSc作为模板转化更多PrPc。组织学上呈海绵状变性。",
     "Enfermedades prionicas: conversion de PrPc a PrPSc. PrPSc actua como plantilla. Degeneracion espongiforme en histologia."),
    ("A 25F has multiple cafe-au-lait spots, axillary freckling, and bilateral acoustic neuromas. What genetic syndrome is most likely?",
     ["Neurofibromatosis type 2 (NF2)", "Neurofibromatosis type 1 (NF1)", "Tuberous sclerosis", "Von Hippel-Lindau disease", "Sturge-Weber syndrome"], 0,
     "NF2 = bilateral acoustic neuromas (vestibular schwannomas) + meningiomas + juvenile cataracts. NF2 gene on chr 22 encodes merlin (schwannomin). NF1 = cafe-au-lait + neurofibromas + Lisch nodules.",
     "NF2 = 双侧听神经瘤（前庭神经鞘瘤）+ 脑膜瘤 + 青少年白内障。NF2基因在22号染色体，编码merlin蛋白。NF1 = 牛奶咖啡斑 + 神经纤维瘤 + Lisch结节。",
     "NF2 = schwannomas vestibulares bilaterales + meningiomas + cataratas juveniles. Gen NF2 en cromosoma 22 (merlin)."),
    ("Dystrophic calcification occurs in the setting of which of the following?",
     ["Normal serum calcium + damaged tissue", "Hypercalcemia + normal tissue", "Hyperphosphatemia + normal tissue", "Hypocalcemia + damaged tissue", "Normal calcium + normal tissue"], 0,
     "Dystrophic calcification = calcium deposits in damaged/necrotic tissue with NORMAL serum calcium. Metastatic calcification = calcium deposits in normal tissue with HYPERcalcemia.",
     "营养不良性钙化 = 钙沉积在受损/坏死组织 + 血钙正常。转移性钙化 = 钙沉积在正常组织 + 高钙血症。",
     "Calcificacion distrofica: deposito de calcio en tejido danado + calcemia normal. Calcificacion metastasica: tejido normal + hipercalcemia."),
    ("Which immunoglobulin is elevated in multiple myeloma, and what is seen on serum protein electrophoresis?",
     ["IgG (most common) — M-spike in gamma region", "IgM — broad gamma peak", "IgA — M-spike in beta region", "IgE — no M-spike", "IgD — polyclonal gamma peak"], 0,
     "Multiple myeloma: monoclonal plasma cell proliferation → monoclonal Ig (most commonly IgG or IgA) → M-spike on SPEP. Associated with lytic bone lesions, hypercalcemia, renal failure, anemia (CRAB).",
     "多发性骨髓瘤：单克隆浆细胞增生→单克隆Ig（最常见IgG或IgA）→SPEP上M峰。与溶骨性病变、高钙血症、肾衰竭、贫血（CRAB）相关。",
     "Mieloma multiple: proliferacion monoclonal de celulas plasmaticas → Ig monoclonal (IgG o IgA) → pico M en SPEP. Lesiones liticas, hipercalcemia, IR, anemia."),
    ("Which finding distinguishes transudative from exudative pleural effusion by Light criteria?",
     ["Pleural fluid protein/serum protein > 0.5", "Pleural fluid pH < 7.2", "Pleural fluid glucose < 60", "WBC count > 10,000", "Specific gravity > 1.020"], 0,
     "Light criteria for exudate: (1) pleural protein/serum protein > 0.5, (2) pleural LDH/serum LDH > 0.6, (3) pleural LDH > 2/3 upper limit of serum LDH. Any 1 = exudate. Transudate satisfies none.",
     "Light标准：渗出液满足任一：(1)胸水蛋白/血清蛋白>0.5，(2)胸水LDH/血清LDH>0.6，(3)胸水LDH>血清上限值2/3。漏出液不满足任何标准。",
     "Criterios de Light para exudado: (1) prot pleura/suero > 0.5, (2) LDH pleura/suero > 0.6, (3) LDH pleura > 2/3 lim sup. Cualquiera = exudado."),
    ("A 55M smoker has squamous cell carcinoma of the lung. Which paraneoplastic syndrome is most associated with this histology?",
     ["Hypercalcemia (PTHrP)", "SIADH", "Cushing syndrome (ACTH)", "Lambert-Eaton syndrome", "Carcinoid syndrome"], 0,
     "Squamous cell lung cancer → PTHrP → hypercalcemia. Small cell lung cancer → SIADH, Cushing (ACTH), Lambert-Eaton. Adenocarcinoma → hypertrophic osteoarthropathy.",
     "肺鳞状细胞癌→PTHrP→高钙血症。小细胞肺癌→SIADH、Cushing（ACTH）、Lambert-Eaton。腺癌→肥大性骨关节病。",
     "Ca escamoso de pulmon → PTHrP → hipercalcemia. Ca de celulas pequenas → SIADH, Cushing, Lambert-Eaton. Adenocarcinoma → osteoartropatia hipertrofica."),
    ("A renal biopsy shows 'wire-loop' lesions on light microscopy and subendothelial deposits on EM. What disease?",
     ["Diffuse proliferative lupus nephritis (Class IV)", "Membranous nephropathy", "Minimal change disease", "Post-streptococcal GN", "IgA nephropathy"], 0,
     "Diffuse proliferative lupus nephritis (Class IV) shows wire-loop lesions (thickened capillary walls), subendothelial immune deposits, and 'full-house' immunofluorescence (IgG, IgM, IgA, C3, C1q). Most severe form of lupus nephritis.",
     "弥漫增生性狼疮肾炎（IV型）显示铁丝圈病变（毛细血管壁增厚）、内皮下免疫复合物沉积和满堂亮免疫荧光。最严重的狼疮肾炎类型。",
     "Nefritis lupica proliferativa difusa (Clase IV): lesiones en asa de alambre, depositos subendoteliales, inmunofluorescencia completa."),
    ("Which gene mutation is found in >90% of chronic myeloid leukemia (CML) cases?",
     ["BCR-ABL (t(9;22) Philadelphia chromosome)", "JAK2 V617F", "FLT3-ITD", "PML-RARA (t(15;17))", "NPM1"], 0,
     "CML is defined by t(9;22) producing BCR-ABL fusion with constitutive tyrosine kinase activity. Treatment: imatinib and other TKIs. JAK2 V617F = polycythemia vera, essential thrombocythemia. PML-RARA = APL.",
     "CML由t(9;22)定义，产生BCR-ABL融合蛋白，具有组成性酪氨酸激酶活性。治疗：伊马替尼和其他TKIs。JAK2 V617F = 真性红细胞增多症、原发性血小板增多症。",
     "LMC: t(9;22) BCR-ABL, actividad tirosina quinasa constitutiva. Tratamiento: imatinib y otros ITK."),
]

for q in path_qs_step1:
    q(next_id, 'step1', 'Pathology', *q); next_id += 1

# --- Physiology (15 questions) ---
phys_qs_step1 = [
    ("In a normal cardiac cycle, when does the mitral valve OPEN?",
     ["When left ventricular pressure falls below left atrial pressure", "When left ventricular pressure exceeds aortic pressure", "At the start of QRS complex", "At the peak of T wave", "When left atrial pressure exceeds 40 mmHg"], 0,
     "Mitral valve opens when LV pressure falls below LA pressure (early diastole, after isovolumetric relaxation). Closes when LV pressure exceeds LA pressure (start of systole). Aortic valve opens when LV pressure > aortic pressure.",
     "二尖瓣在左室压低于左房压时打开（舒张早期，等容舒张后）。左室压超过左房压时关闭（收缩期开始时）。主动脉瓣在左室压>主动脉压时打开。",
     "Valvula mitral se abre cuando presion VI < presion AI (diastole temprana). Se cierra cuando presion VI > presion AI (inicio de sistole)."),
    ("What happens to GFR when the afferent arteriole constricts?",
     ["Decreases", "Increases", "No change", "Initially increases then decreases", "Depends on efferent arteriole"], 0,
     "Afferent arteriole constriction → decreased renal blood flow → decreased GFR. Efferent arteriole constriction → increased glomerular pressure → increased GFR (unless severe, then decreases).",
     "入球小动脉收缩→肾血流量减少→GFR降低。出球小动脉收缩→肾小球压力升高→GFR升高（除非严重，则降低）。",
     "Constriccion arteriola aferente → disminuye flujo sanguineo renal → disminuye TFG. Constriccion eferente → aumenta presion glomerular → aumenta TFG."),
    ("Which part of the nephron is impermeable to water even in the presence of ADH?",
     ["Thick ascending limb", "Proximal convoluted tubule", "Descending limb of loop of Henle", "Cortical collecting duct", "Medullary collecting duct"], 0,
     "Thick ascending limb is ALWAYS impermeable to water (no aquaporins). This segment actively reabsorbs Na/K/Cl via NKCC2 cotransporter, creating the medullary osmotic gradient. Loop diuretics (furosemide) act here.",
     "髓袢升支粗段始终不透水（无水通道蛋白）。此段通过NKCC2共转运体主动重吸收Na/K/Cl，形成髓质渗透压梯度。袢利尿剂（呋塞米）作用于此。",
     "Rama ascendente gruesa SIEMPRE impermeable al agua. Reabsorbe Na/K/Cl via NKCC2 creando gradiente osmotico medular. Furosemida actua aqui."),
    ("Which hormone increases calcium levels by acting on bone, kidney, and intestine?",
     ["Parathyroid hormone (PTH)", "Calcitonin", "Vitamin D (calcitriol)", "Thyroid hormone", "Growth hormone"], 0,
     "PTH increases serum Ca2+: (1) bone resorption, (2) kidney: increased Ca2+ reabsorption + decreased phosphate reabsorption + stimulates 1-alpha-hydroxylase, (3) indirectly increases intestinal Ca2+ absorption via vitamin D activation.",
     "PTH升高血钙：(1)骨吸收，(2)肾脏：增加钙重吸收+减少磷酸盐重吸收+刺激1α羟化酶，(3)通过激活维生素D间接增加肠道钙吸收。",
     "PTH aumenta Ca2+: (1) resorcion osea, (2) rinon: reabsorcion Ca2+ + disminuye fosfato + activa 1-alfa-hidroxilasa, (3) absorcion intestinal via vitamina D."),
    ("During exercise, which vascular bed experiences the greatest increase in blood flow?",
     ["Skeletal muscle", "Cerebral", "Coronary", "Cutaneous", "Renal"], 0,
     "Skeletal muscle blood flow increases dramatically during exercise (vasodilation from local metabolites — adenosine, lactate, K+, CO2). Coronary flow increases. Cerebral flow maintained constant. Splanchnic and renal flow decrease.",
     "运动时骨骼肌血流量急剧增加（局部代谢产物——腺苷、乳酸、K+、CO2引起的血管扩张）。冠脉流量增加。脑血流量保持不变。内脏和肾血流量减少。",
     "Flujo muscular esqueletico aumenta con ejercicio (vasodilatacion por metabolitos: adenosina, lactato, K+, CO2). Flujo coronario aumenta, cerebral constante."),
    ("What is the effect of sympathetic stimulation on the heart?",
     ["Increased heart rate, contractility, and conduction velocity", "Decreased heart rate, increased contractility", "Increased heart rate, decreased contractility", "Decreased heart rate and contractility", "No effect on heart rate, only contractility"], 0,
     "Sympathetic stimulation (norepinephrine, beta-1 receptors): positive chronotropic (HR), inotropic (contractility), dromotropic (conduction velocity), lusitropic (relaxation). Parasympathetic (ACh, M2): negative chronotropic, dromotropic.",
     "交感神经刺激（去甲肾上腺素，β1受体）：正性变时、变力、变传导、舒张效应。副交感神经（ACh，M2）：负性变时、变传导。",
     "Estimulacion simpatica (NA, beta-1): cronotropico, inotropico, dromotropico, lusitropico positivos. Parasimpatico (ACh, M2): cronotropico, dromotropico negativos."),
    ("What happens to serum potassium during acute metabolic acidosis?",
     ["Increases (shifts out of cells)", "Decreases (shifts into cells)", "No change", "Initially increases then decreases", "Only changes in respiratory acidosis"], 0,
     "Acute metabolic acidosis → H+ enters cells, K+ shifts out to maintain electroneutrality → hyperkalemia. Opposite in alkalosis: H+ exits cells, K+ shifts in → hypokalemia. 0.1 pH decrease ≈ 0.6 mEq/L K+ increase.",
     "急性代谢性酸中毒→H+进入细胞，K+移出细胞以维持电中性→高钾血症。碱中毒相反。pH降低0.1≈血钾升高0.6 mEq/L。",
     "Acidosis metabolica aguda → H+ entra celulas, K+ sale → hiperkalemia. Alcalosis: lo opuesto. Disminucion pH 0.1 ≈ aumento K+ 0.6 mEq/L."),
    ("Which ECG finding is characteristic of hyperkalemia?",
     ["Peaked T waves", "ST depression", "Prolonged QT interval", "U waves", "J point elevation"], 0,
     "Hyperkalemia ECG progression: peaked T waves → loss of P waves → widened QRS → sine wave pattern → ventricular fibrillation. Hypokalemia: U waves, flattened T waves, ST depression.",
     "高钾血症ECG演变：T波高尖→P波消失→QRS增宽→正弦波→室颤。低钾血症：U波、T波低平、ST段压低。",
     "Progresion ECG hiperkalemia: T picuda → perdida ondas P → QRS ancho → patron sinusoidal → FV. Hipokalemia: ondas U, T plana."),
    ("Which area of the brain is responsible for Broca (expressive) aphasia?",
     ["Inferior frontal gyrus (dominant hemisphere)", "Superior temporal gyrus", "Angular gyrus", "Supramarginal gyrus", "Arcuate fasciculus"], 0,
     "Broca area = inferior frontal gyrus (Brodmann 44, 45), dominant hemisphere → expressive aphasia (non-fluent, intact comprehension). Wernicke area = superior temporal gyrus → receptive aphasia (fluent, impaired comprehension).",
     "Broca区 = 额下回（Brodmann 44、45），优势半球→表达性失语（非流利，理解完好）。Wernicke区 = 颞上回→感受性失语（流利，理解受损）。",
     "Area de Broca = giro frontal inferior (dominante) → afasia expresiva. Area de Wernicke = giro temporal superior → afasia receptiva."),
    ("A patient has normal PACO2 of 40 mmHg and elevated serum HCO3- of 32 mEq/L. What is the primary disorder?",
     ["Metabolic alkalosis", "Respiratory alkalosis", "Metabolic acidosis", "Respiratory acidosis", "Mixed disorder"], 0,
     "Elevated HCO3- (>26) with normal PACO2 = metabolic alkalosis (uncompensated). If compensated, PACO2 would be elevated. pH would be >7.45 in primary metabolic alkalosis.",
     "HCO3-升高（>26）且PACO2正常 = 代谢性碱中毒（失代偿）。如果已代偿，PACO2会升高。原发性代谢性碱中毒时pH>7.45。",
     "HCO3- elevado (>26) con PACO2 normal = alcalosis metabolica (no compensada). Si compensada, PACO2 estaria elevado."),
    ("Which cell type produces surfactant in the lungs?",
     ["Type II pneumocytes", "Type I pneumocytes", "Club cells (Clara cells)", "Alveolar macrophages", "Goblet cells"], 0,
     "Type II pneumocytes produce surfactant (dipalmitoylphosphatidylcholine, DPPC) which reduces surface tension. Also serve as stem cells for Type I cells. Surfactant production begins at ~24 weeks gestation.",
     "II型肺泡细胞产生表面活性物质（二棕榈酰磷脂酰胆碱，DPPC），降低表面张力。也作为I型细胞的干细胞。表面活性物质从约孕24周开始产生。",
     "Neumocitos tipo II producen surfactante (DPPC) que reduce tension superficial. Tambien son celulas madre para tipo I. Produccion desde ~24 sem de gestacion."),
    ("What is the primary mechanism of action of loop diuretics like furosemide?",
     ["Inhibit Na-K-2Cl cotransporter (NKCC2) in thick ascending limb", "Inhibit Na-Cl cotransporter in distal convoluted tubule", "Block aldosterone receptor in collecting duct", "Osmotic diuresis", "Carbonic anhydrase inhibition"], 0,
     "Furosemide inhibits NKCC2 in thick ascending limb → decreased Na/K/Cl reabsorption → decreased medullary hypertonicity → decreased water reabsorption → potent diuresis. Also causes Ca2+ and Mg2+ wasting.",
     "呋塞米抑制髓袢升支粗段的NKCC2→减少Na/K/Cl重吸收→降低髓质高渗性→减少水重吸收→强力利尿。同时导致钙和镁丢失。",
     "Furosemida inhibe NKCC2 en rama ascendente gruesa → disminuye reabsorcion Na/K/Cl → menor hipertonicidad medular → diuresis potente. Perdida de Ca2+ y Mg2+."),
    ("What is the physiologic response to high altitude (hypobaric hypoxia)?",
     ["Increased ventilation, increased 2,3-BPG, increased erythropoietin", "Decreased ventilation, decreased hemoglobin", "Increased ventilation, decreased erythropoietin", "Bradycardia, decreased cardiac output", "Decreased 2,3-BPG, increased oxygen affinity"], 0,
     "Altitude adaptation: (1) acute: hyperventilation (hypoxic ventilatory response), (2) subacute: increased 2,3-BPG (right-shifts O2 curve), (3) chronic: increased EPO → polycythemia. May cause acute mountain sickness, HAPE, HACE.",
     "高原适应：(1)急性：过度通气，(2)亚急性：2,3-BPG升高（氧合曲线右移），(3)慢性：EPO升高→红细胞增多。可能引起急性高山病、HAPE、HACE。",
     "Adaptacion a altitud: (1) aguda: hiperventilacion, (2) subaguda: aumento 2,3-BPG (desplaza curva O2 derecha), (3) cronica: aumento EPO → policitemia."),
    ("Which nerve is at risk during thyroidectomy, and what happens if it is injured?",
     ["Recurrent laryngeal nerve — hoarseness (unilateral) or stridor (bilateral)", "Superior laryngeal nerve — loss of high-pitched voice", "Vagus nerve — bradycardia", "Phrenic nerve — diaphragmatic paralysis", "Hypoglossal nerve — tongue deviation"], 0,
     "Recurrent laryngeal nerve (branch of vagus) innervates all laryngeal muscles except cricothyroid. Unilateral injury → hoarseness. Bilateral injury → stridor, respiratory distress — airway emergency. Superior laryngeal supplies cricothyroid.",
     "喉返神经支配除环甲肌外的所有喉肌。单侧损伤→声音嘶哑。双侧损伤→喘鸣、呼吸困难、紧急气道。喉上神经支配环甲肌。",
     "Nervio laringeo recurrente inerva todos musculos laringeos excepto cricotiroideo. Lesion unilateral → ronquera. Bilateral → estridor, emergencia via aerea."),
    ("Which ion is primarily responsible for the plateau phase (phase 2) of the cardiac action potential?",
     ["Calcium (L-type Ca2+ channels)", "Sodium", "Potassium", "Chloride", "Magnesium"], 0,
     "Phase 2 (plateau): balance between Ca2+ influx (L-type channels) and K+ efflux (delayed rectifier). This sustained depolarization prevents tetany and allows complete emptying. Phase 0: fast Na+ influx (upstroke). Phase 3: K+ efflux (repolarization).",
     "第2期（平台期）：钙内流（L型通道）与钾外流（延迟整流）的平衡。此持续去极化防止强直收缩，允许完全排空。第0期：快速钠内流。第3期：钾外流（复极）。",
     "Fase 2 (meseta): equilibrio entre entrada Ca2+ (canales L) y salida K+. Impide tetania. Fase 0: entrada rapida Na+. Fase 3: salida K+ (repolarizacion)."),
]

for q in phys_qs_step1:
    q(next_id, 'step1', 'Physiology', *q); next_id += 1

# --- Pharmacology (15 questions) ---
pharm_qs_step1 = [
    ("What is the mechanism of action of aspirin at low doses (81 mg)?",
     ["Irreversibly inhibits COX-1 → decreased thromboxane A2 → antiplatelet effect", "Reversibly inhibits COX-2 → anti-inflammatory", "Inhibits phosphodiesterase → vasodilation", "Blocks ADP receptors on platelets", "Activates antithrombin III"], 0,
     "Low-dose aspirin (81mg) irreversibly acetylates COX-1, preventing thromboxane A2 production in platelets for their lifespan (7-10 days). Higher doses also inhibit COX-2 (anti-inflammatory). Clopidogrel blocks P2Y12 (ADP receptor).",
     "低剂量阿司匹林不可逆地乙酰化COX-1，阻止血小板在生命周期（7-10天）内产生血栓素A2。大剂量也抑制COX-2（抗炎）。氯吡格雷阻断P2Y12（ADP受体）。",
     "Aspirina dosis baja: inhibe irreversiblemente COX-1 → disminuye tromboxano A2 → antiplaquetario. Clopidogrel bloquea P2Y12."),
    ("Which adverse effect is most associated with ACE inhibitors?",
     ["Dry cough and angioedema", "Hypokalemia", "Gingival hyperplasia", "Lupus-like syndrome", "Ototoxicity"], 0,
     "ACE inhibitors → decreased bradykinin breakdown → increased bradykinin → dry cough (10-20%), angioedema. Also cause hyperkalemia (decreased aldosterone). ARBs do not increase bradykinin → no cough. Contraindicated in pregnancy.",
     "ACE抑制剂→减少缓激肽降解→缓激肽升高→干咳（10-20%）、血管性水肿。也引起高钾血症（醛固酮减少）。ARB不增加缓激肽→无干咳。妊娠期禁用。",
     "IECA: disminuye degradacion bradiquinina → aumento bradiquinina → tos seca, angioedema. ARA-II no → sin tos. Contraindicados en embarazo."),
    ("Which antibiotic class is contraindicated in children due to risk of cartilage damage?",
     ["Fluoroquinolones (e.g., ciprofloxacin)", "Penicillins", "Cephalosporins", "Macrolides", "Tetracyclines"], 0,
     "Fluoroquinolones cause cartilage toxicity in animal studies → generally avoided in children. Also cause tendon rupture in adults, QT prolongation. Tetracyclines cause teeth discoloration in children <8 years.",
     "氟喹诺酮类在动物研究中引起软骨毒性→儿童一般避免使用。也引起成人肌腱断裂、QT间期延长。四环素类引起8岁以下儿童牙齿变色。",
     "Fluoroquinolonas causan toxicidad cartilaginosa → evitar en ninos. Tambien ruptura tendones, prolongacion QT. Tetraciclinas decoloran dientes en <8 anos."),
    ("What is the antidote for heparin overdose?",
     ["Protamine sulfate", "Vitamin K", "Fresh frozen plasma", "Idarucizumab", "Andexanet alfa"], 0,
     "Protamine sulfate (positively charged) binds heparin (negatively charged) → reverses anticoagulation. Vitamin K reverses warfarin. Idarucizumab reverses dabigatran. Andexanet alfa reverses factor Xa inhibitors.",
     "鱼精蛋白（带正电荷）结合肝素（带负电荷）→逆转抗凝。维生素K对抗华法林。依达赛珠单抗对抗达比加群。Andexanet alfa对抗Xa因子抑制剂。",
     "Protamina (positiva) se une a heparina (negativa) → revierte anticoagulacion. Vitamina K revierte warfarina. Idarucizumab revierte dabigatran."),
    ("Which antiepileptic drug can cause megaloblastic anemia by interfering with folate metabolism?",
     ["Phenytoin", "Valproic acid", "Levetiracetam", "Lamotrigine", "Topiramate"], 0,
     "Phenytoin decreases folate absorption and increases folate metabolism → megaloblastic anemia with prolonged use. Also causes gingival hyperplasia, hirsutism, coarse facies, peripheral neuropathy, osteomalacia, and Stevens-Johnson syndrome.",
     "苯妥英钠减少叶酸吸收并增加叶酸代谢→长期使用导致巨幼红细胞性贫血。也引起牙龈增生、多毛症、面容粗陋、周围神经病变、骨软化症和Stevens-Johnson综合征。",
     "Fenitoina disminuye absorcion y aumenta metabolismo de folato → anemia megaloblastica. Tambien hiperplasia gingival, hirsutismo, SJS."),
    ("What is the mechanism of action of metformin?",
     ["Decreased hepatic gluconeogenesis + increased peripheral insulin sensitivity", "Increased insulin secretion from beta cells", "Decreased carbohydrate absorption", "GLP-1 receptor agonism", "SGLT2 inhibition"], 0,
     "Metformin: primary effect is decreased hepatic gluconeogenesis via AMPK activation. Also increases peripheral glucose uptake. Does NOT stimulate insulin secretion (no hypoglycemia risk alone). First-line for type 2 DM.",
     "二甲双胍：主要作用是激活AMPK减少肝糖异生。同时增加外周葡萄糖摄取。不刺激胰岛素分泌（单用不引起低血糖）。2型糖尿病一线用药。",
     "Metformina: disminuye gluconeogenesis hepatica via AMPK + aumento captacion periferica de glucosa. NO estimula secrecion de insulina. Primera linea DM2."),
    ("Which local anesthetic is contraindicated for Bier block (IV regional anesthesia) due to cardiotoxicity?",
     ["Bupivacaine", "Lidocaine", "Prilocaine", "Ropivacaine", "Chloroprocaine"], 0,
     "Bupivacaine has high cardiotoxicity (binds tightly to Na+ channels in cardiac tissue, slow dissociation) → contraindicated for Bier block. Lidocaine is preferred. Bupivacaine cardiotoxicity treatment: IV lipid emulsion (Intralipid 20%).",
     "布比卡因心脏毒性高→禁用于Bier阻滞麻醉。首选利多卡因。布比卡因心脏毒性治疗：静脉用脂肪乳剂（20%英脱利匹特）。",
     "Bupivacaina: alta cardiotoxicidad → contraindicada para bloqueo de Bier. Lidocaina preferida. Tratamiento toxicidad: emulsion lipidica IV 20%."),
    ("Warfarin inhibits which enzyme in the vitamin K cycle?",
     ["Vitamin K epoxide reductase (VKORC1)", "Gamma-glutamyl carboxylase", "Vitamin K reductase", "Cytochrome P450 2C9", "Thrombin"], 0,
     "Warfarin inhibits VKORC1 → prevents reduction of vitamin K epoxide to active vitamin K → decreased synthesis of factors II, VII, IX, X, protein C and S. Monitored by PT/INR. CYP2C9 metabolizes warfarin.",
     "华法林抑制VKORC1→阻止维生素K环氧化物还原为活性维生素K→减少因子II、VII、IX、X和蛋白C、S合成。通过PT/INR监测。CYP2C9代谢华法林。",
     "Warfarina inhibe VKORC1 → bloquea reduccion de epoxido de vitamina K → disminuye factores II, VII, IX, X, proteina C y S. Monitorizar con INR."),
    ("Which medication used for bipolar disorder requires monitoring of thyroid and renal function?",
     ["Lithium", "Valproic acid", "Carbamazepine", "Lamotrigine", "Olanzapine"], 0,
     "Lithium: narrow therapeutic index. Adverse effects: hypothyroidism (monitor TSH), nephrogenic diabetes insipidus (monitor renal function, urine output), tremor, weight gain, ECG changes. Teratogenic (Ebstein anomaly).",
     "锂盐：治疗指数窄。不良反应：甲状腺功能减退（监测TSH）、肾性尿崩症（监测肾功能、尿量）、震颤、体重增加、ECG变化。致畸（Ebstein畸形）。",
     "Litio: indice terapeutico estrecho. Efectos: hipotiroidismo, diabetes insipida nefrogenica, temblor, aumento peso. Teratogenico (anomalia Ebstein)."),
    ("Which antibiotic causes red-orange discoloration of bodily fluids?",
     ["Rifampin", "Isoniazid", "Pyrazinamide", "Ethambutol", "Streptomycin"], 0,
     "Rifampin causes red-orange discoloration of urine, tears, sweat, and contact lenses. It is a potent CYP450 inducer. Part of RIPE therapy for TB along with Isoniazid, Pyrazinamide, Ethambutol.",
     "利福平导致尿液、泪液、汗液和隐形眼镜呈红橙色变色。是强效CYP450诱导剂。与异烟肼、吡嗪酰胺、乙胺丁醇组成RIPE抗结核方案。",
     "Rifampicina causa coloracion rojo-naranja de orina, lagrimas, sudor. Potente inductor CYP450. Parte de terapia RIPE para TB."),
    ("Which antihypertensive is contraindicated in pregnancy due to fetal renal malformations?",
     ["ACE inhibitors (e.g., lisinopril)", "Methyldopa", "Labetalol", "Nifedipine", "Hydralazine"], 0,
     "ACE inhibitors/ARBs are contraindicated in pregnancy → fetal renal dysgenesis, oligohydramnios, pulmonary hypoplasia, fetal death. Safe antihypertensives in pregnancy: methyldopa (first line), labetalol, nifedipine, hydralazine.",
     "ACE抑制剂/ARB妊娠期禁用→胎儿肾发育不良、羊水过少、肺发育不全、胎儿死亡。妊娠期安全降压药：甲基多巴（一线）、拉贝洛尔、硝苯地平、肼苯哒嗪。",
     "IECA/ARA-II contraindicados en embarazo → disgenesia renal fetal, oligohidramnios. Antihipertensivos seguros: metildopa, labetalol, nifedipino, hidralazina."),
    ("What is the mechanism of action of omeprazole?",
     ["Irreversible inhibition of H+/K+ ATPase in parietal cells", "H2 receptor antagonism", "Prostaglandin analog", "Antacid neutralization", "Mucosal protectant"], 0,
     "Omeprazole (PPI) irreversibly inhibits H+/K+ ATPase (proton pump) in gastric parietal cells. Prodrug activated in acidic environment. Most effective acid suppressants. Long-term use: increased risk of C. diff, fractures, B12 deficiency.",
     "奥美拉唑不可逆地抑制胃壁细胞H+/K+ ATP酶（质子泵）。前药在酸性环境中激活。最强效抑酸药。长期使用：增加艰难梭菌感染、骨折、维生素B12缺乏风险。",
     "Omeprazol: inhibe irreversiblemente H+/K+ ATPasa en celulas parietales. Profarmaco activado en medio acido. Uso prolongado: riesgo C. diff, fracturas."),
    ("Naloxone reverses overdose of which class of drugs?",
     ["Opioids (e.g., morphine, heroin)", "Benzodiazepines", "Barbiturates", "Ethanol", "Cocaine"], 0,
     "Naloxone = competitive opioid receptor antagonist (mu, kappa, delta). Reverses respiratory depression from opioid overdose within 2-5 minutes. Short half-life (30-90 min) — may need repeat dosing. Can cause acute withdrawal.",
     "纳洛酮 = 竞争性阿片受体拮抗剂，逆转阿片过量导致的呼吸抑制，2-5分钟内起效。半衰期短（30-90分钟）——可能需要重复给药。可能引起急性戒断症状。",
     "Naloxona: antagonista opioide competitivo. Revierte depresion respiratoria en 2-5 min. Vida media corta (30-90 min). Puede causar abstinencia aguda."),
    ("What is a serious adverse effect of clozapine requiring regular monitoring?",
     ["Agranulocytosis — weekly CBC monitoring", "Tardive dyskinesia", "Hyperprolactinemia", "QT prolongation", "Weight gain"], 0,
     "Clozapine causes agranulocytosis in ~1% of patients. Requires weekly CBC for first 6 months, then biweekly, then monthly. Reserved for treatment-resistant schizophrenia. Other effects: seizures (dose-dependent), myocarditis, severe constipation.",
     "氯氮平约1%患者发生粒细胞缺乏症。需前6个月每周查血常规，之后每两周一次，然后每月一次。用于难治性精神分裂症。其他不良反应：癫痫发作、心肌炎、严重便秘。",
     "Clozapina: agranulocitosis en ~1%. Requiere CBC semanal primeros 6 meses. Reservado para esquizofrenia resistente. Tambien convulsiones, miocarditis."),
    ("Which antidote is used for acetaminophen (paracetamol) overdose?",
     ["N-acetylcysteine (NAC)", "Flumazenil", "Naloxone", "Fomepizole", "Sodium bicarbonate"], 0,
     "NAC replenishes glutathione → enhances non-toxic metabolism of NAPQI (toxic acetaminophen metabolite). Most effective within 8 hours of overdose. Use Rumack-Matthew nomogram to determine need for treatment based on serum level and time post-ingestion.",
     "NAC补充谷胱甘肽→增强NAPQI的无毒代谢途径。过量后8小时内最有效。使用Rumack-Matthew列线图根据血清水平和摄入后时间确定治疗需求。",
     "NAC repone glutatión → mejora metabolismo no toxico de NAPQI. Mas efectivo dentro 8h post-sobredosis. Usar nomograma Rumack-Matthew."),
]

for q in pharm_qs_step1:
    q(next_id, 'step1', 'Pharmacology', *q); next_id += 1

# --- Anatomy (15 questions) ---
anatomy_qs_step1 = [
    ("Which structure passes through the carpal tunnel?",
     ["Median nerve and flexor tendons", "Ulnar nerve only", "Radial nerve only", "Radial artery only", "Ulnar artery and nerve"], 0,
     "Carpal tunnel contains: median nerve + 9 tendons (4 FDS, 4 FDP, FPL). Carpal tunnel syndrome: compression of median nerve → paresthesias in thumb, index, middle, and radial half of ring finger. Thenar atrophy in late stages.",
     "腕管内容：正中神经 + 9条肌腱（4条指浅屈肌、4条指深屈肌、1条拇长屈肌）。腕管综合征：正中神经受压→拇指、食指、中指和环指桡侧半感觉异常，晚期大鱼际肌萎缩。",
     "Tunel carpiano: nervio mediano + 9 tendones. Sindrome: compresion mediano → parestesias pulgar, indice, medio, mitad radial anular. Atrofia tenar tardia."),
    ("Which nerve is most commonly injured in anterior shoulder dislocation?",
     ["Axillary nerve", "Radial nerve", "Median nerve", "Musculocutaneous nerve", "Suprascapular nerve"], 0,
     "Axillary nerve (C5-C6) wraps around surgical neck of humerus → injured in anterior shoulder dislocation or proximal humerus fracture. Results in deltoid paralysis + loss of sensation over lateral shoulder (regimental badge area).",
     "腋神经绕行肱骨外科颈→前肩关节脱位或肱骨近端骨折时受损。导致三角肌麻痹+肩外侧感觉丧失。",
     "Nervio axilar (C5-C6): rodea cuello quirurgico humero. Lesion en luxacion anterior hombro → paralisis deltoides + perdida sensibilidad hombro lateral."),
    ("What is the blood supply to the femoral head at greatest risk in femoral neck fractures?",
     ["Medial circumflex femoral artery", "Lateral circumflex femoral artery", "Obturator artery", "Superior gluteal artery", "Inferior gluteal artery"], 0,
     "Medial circumflex femoral artery supplies most of the femoral head via lateral epiphyseal vessels. Femoral neck fractures can disrupt this blood supply → avascular necrosis (AVN) of femoral head.",
     "旋股内侧动脉通过外侧骨骺血管供应大部分股骨头。股骨颈骨折会破坏此血供→股骨头缺血坏死。",
     "Arteria circunfleja femoral medial irriga mayor parte de cabeza femoral. Fractura cuello femoral → interrupcion → necrosis avascular."),
    ("After a mastectomy with axillary lymph node dissection, a patient cannot raise her arm above horizontal. Which nerve is injured?",
     ["Long thoracic nerve", "Thoracodorsal nerve", "Spinal accessory nerve", "Dorsal scapular nerve", "Axillary nerve"], 0,
     "Long thoracic nerve (C5-C7) innervates serratus anterior → winging of scapula + inability to abduct arm above 90 degrees. Injured during mastectomy, axillary dissection, or carrying heavy weight on shoulder.",
     "胸长神经支配前锯肌→翼状肩胛+手臂外展不能超过90度。乳房切除术、腋窝清扫或肩部负重时受损。",
     "Nervio toracico largo (C5-C7): inerva serrato anterior → escapula alada + no puede abducir brazo >90 grados. Lesion en mastectomia."),
    ("Which coronary artery supplies the SA node in 60% of the population?",
     ["Right coronary artery (RCA)", "Left anterior descending (LAD)", "Left circumflex (LCx)", "Left main coronary artery", "Posterior descending artery"], 0,
     "RCA supplies SA node in 60% of people (right dominant circulation). LCx supplies SA node in 40%. RCA also supplies AV node (90%), right ventricle, and posterior-inferior LV.",
     "60%人群RCA供血窦房结（右优势型）。40%人群LCx供血。RCA也供血房室结（90%）、右心室和下后壁左室。",
     "RCA irriga nodulo SA en 60% (dominancia derecha). LCx en 40%. RCA tambien irriga nodulo AV (90%), ventriculo derecho y LV posteroinferior."),
    ("Which structure lies posterior to the medial malleolus (tarsal tunnel)?",
     ["Tibialis posterior tendon, flexor digitorum longus, posterior tibial artery & nerve, flexor hallucis longus", "Peroneus longus and brevis tendons", "Anterior tibial artery", "Extensor hallucis longus tendon", "Achilles tendon"], 0,
     "Tarsal tunnel contents (Tom, Dick, And Very Nervous Harry): Tibialis posterior, flexor Digitorum longus, posterior tibial Artery, posterior tibial Vein, posterior tibial Nerve, flexor Hallucis longus.",
     "踝管内容（记忆口诀）：胫骨后肌腱、趾长屈肌腱、胫后动脉、胫后静脉、胫后神经、踇长屈肌腱。",
     "Tunel tarsiano: tendones tibial posterior, flexor largo dedos, flexor largo hallux, arteria, vena y nervio tibial posterior."),
    ("The ulnar nerve passes through which structure at the elbow?",
     ["Cubital tunnel", "Carpal tunnel", "Guyon canal", "Spiral groove", "Tarsal tunnel"], 0,
     "Ulnar nerve passes posterior to medial epicondyle in cubital tunnel → most common site of ulnar nerve entrapment (cubital tunnel syndrome). Also passes through Guyon canal at wrist. Causes claw hand, hypothenar atrophy.",
     "尺神经在肘管中走行于肱骨内上髁后方→最常见的尺神经卡压部位。也通过腕部Guyon管。导致爪形手、小鱼际肌萎缩。",
     "Nervio cubital pasa posterior a epicondilo medial en tunel cubital → sitio mas comun de atrapamiento. Tambien canal de Guyon en muneca."),
    ("The gallbladder receives its blood supply from which artery?",
     ["Cystic artery (branch of right hepatic artery)", "Left hepatic artery", "Gastroduodenal artery", "Superior mesenteric artery", "Splenic artery"], 0,
     "Cystic artery is typically a branch of the right hepatic artery. Important to identify during cholecystectomy (Calot triangle: cystic duct, common hepatic duct, cystic artery bordered by liver edge).",
     "胆囊动脉通常是右肝动脉的分支。胆囊切除术中需识别（Calot三角：胆囊管、肝总管、胆囊动脉，以肝缘为界）。",
     "Arteria cistica: rama de arteria hepatica derecha. Identificar en colecistectomia. Triangulo de Calot: conducto cistico, hepatico comun, arteria cistica."),
    ("A patient has weakness of wrist extension and finger extension. Which nerve is injured, and where?",
     ["Radial nerve — spiral groove of humerus", "Median nerve — carpal tunnel", "Ulnar nerve — cubital tunnel", "Axillary nerve — surgical neck", "Musculocutaneous nerve — coracobrachialis"], 0,
     "Radial nerve injury at spiral groove: wrist drop (loss of wrist and finger extensors). Triceps spared (innervation above spiral groove). Saturday night palsy. Sensory loss over dorsal hand (first web space).",
     "桡神经在螺旋沟处损伤：腕下垂、手指不能伸直。肱三头肌不受影响。周末夜麻痹。手背第一指蹼间隙感觉丧失。",
     "Lesion nervio radial en surco espiral: mano caida. Triceps preservado (inervacion proximal). Paralisis del sabado noche. Perdida sensorial dorso mano."),
    ("Which muscle is responsible for abduction of the eye (lateral gaze)?",
     ["Lateral rectus (CN VI — abducens nerve)", "Medial rectus (CN III)", "Superior oblique (CN IV)", "Inferior oblique (CN III)", "Superior rectus (CN III)"], 0,
     "LR6 SO4 AO3: Lateral Rectus → CN VI (Abducens), Superior Oblique → CN IV (Trochlear), All Others → CN III (Oculomotor). Abducens nerve palsy: inability to abduct eye, diplopia on lateral gaze.",
     "外直肌→CN VI（展神经），上斜肌→CN IV（滑车神经），其余眼外肌→CN III（动眼神经）。展神经麻痹：不能外展、向外侧注视复视。",
     "Recto lateral → VI par, Oblicuo superior → IV par, Resto musculos → III par. Paralisis VI: no abduce, diplopia en mirada lateral."),
    ("The inguinal ligament is derived from which structure?",
     ["External oblique aponeurosis", "Internal oblique muscle", "Transversus abdominis muscle", "Rectus sheath", "Lacunar ligament"], 0,
     "Inguinal ligament (Poupart ligament) = rolled-under free edge of external oblique aponeurosis from ASIS to pubic tubercle. Forms floor of inguinal canal. Direct inguinal hernias protrude through Hesselbach triangle above this ligament.",
     "腹股沟韧带 = 腹外斜肌腱膜游离缘卷曲而成，从髂前上棘到耻骨结节。构成腹股沟管的下壁。直疝通过此韧带上方Hesselbach三角突出。",
     "Ligamento inguinal: borde libre de aponeurosis oblicuo externo desde EIAS a tuberculo pubico. Hernias directas protruyen sobre este ligamento."),
    ("Which ligament of the uterus contains the uterine artery?",
     ["Cardinal ligament (transverse cervical/ Mackenrodt ligament)", "Round ligament", "Broad ligament", "Uterosacral ligament", "Ovarian ligament"], 0,
     "Cardinal ligament (Mackenrodt) contains uterine artery and vein. Uterosacral ligament provides major support. Round ligament maintains uterine anteversion. Broad ligament = peritoneal fold (mesosalpinx, mesovarium, mesometrium).",
     "主韧带含子宫动静脉。子宫骶骨韧带提供主要支持。圆韧带维持子宫前倾。阔韧带 = 腹膜皱襞（输卵管系膜、卵巢系膜、子宫系膜）。",
     "Ligamento cardinal (Mackenrodt) contiene arteria y vena uterina. Uterosacro: soporte principal. Redondo: anteversion. Ancho: pliegue peritoneal."),
    ("The popliteal artery divides into which two arteries?",
     ["Anterior tibial artery and posterior tibial artery", "Peroneal artery and dorsalis pedis", "Femoral artery and profunda femoris", "Sural arteries only", "Plantar arteries"], 0,
     "Popliteal artery bifurcates at lower border of popliteus muscle into anterior tibial (passes through interosseous membrane) and posterior tibial arteries. Posterior tibial gives off peroneal (fibular) artery. Dorsalis pedis = continuation of anterior tibial.",
     "腘动脉在腘肌下缘分出胫前动脉和胫后动脉。胫后动脉分出腓动脉。足背动脉 = 胫前动脉的延续。",
     "Arteria poplitea se bifurca en tibial anterior y posterior. Tibial posterior da arteria peronea. Dorsal del pie = continuacion de tibial anterior."),
    ("What does the notochord become in the adult?",
     ["Nucleus pulposus of intervertebral disc", "Vertebral body", "Spinal cord", "Annulus fibrosus", "Neural arch"], 0,
     "Notochord → nucleus pulposus (gelatinous center of intervertebral disc). Vertebral bodies form from sclerotome (paraxial mesoderm). Remnants of notochord may give rise to chordomas (midline tumors, sacrum/clivus).",
     "脊索→髓核（椎间盘胶状中心）。椎体由生骨节（轴旁中胚层）形成。脊索残余可导致脊索瘤（中线肿瘤，骶骨/斜坡）。",
     "Notocorda → nucleo pulposo del disco intervertebral. Cuerpos vertebrales de esclerotomo. Restos notocorda → cordomas (tumores linea media, sacro/clivus)."),
    ("Where does CSF get reabsorbed into the venous system?",
     ["Arachnoid granulations into the superior sagittal sinus", "Choroid plexus", "Foramen of Monro", "Cerebral aqueduct", "Foramen of Magendie"], 0,
     "CSF produced by choroid plexus in ventricles → flows through ventricular system → exits via foramina of Luschka and Magendie into subarachnoid space → reabsorbed via arachnoid granulations into superior sagittal sinus.",
     "CSF由脑室脉络丛产生→流经脑室系统→经Luschka孔和Magendie孔出到蛛网膜下腔→通过蛛网膜颗粒重新吸收到上矢状窦。",
     "LCR producido en plexos coroideos → circula ventriculos → sale por foramenes Luschka y Magendie → espacio subaracnoideo → reabsorbido en granulaciones aracnoideas → seno sagital superior."),
]

for q in anatomy_qs_step1:
    q(next_id, 'step1', 'Anatomy', *q); next_id += 1

# --- Biochemistry (15 questions) ---
biochem_qs_step1 = [
    ("Which enzyme is the rate-limiting step of glycolysis?",
     ["Phosphofructokinase-1 (PFK-1)", "Hexokinase", "Pyruvate kinase", "Phosphoglucose isomerase", "Glyceraldehyde-3-phosphate dehydrogenase"], 0,
     "PFK-1 converts fructose-6-phosphate to fructose-1,6-bisphosphate — rate-limiting step of glycolysis. Activated by AMP, fructose-2,6-bisphosphate. Inhibited by ATP, citrate. Hexokinase is also regulated but PFK-1 is the committed step.",
     "PFK-1将果糖-6-磷酸转化为果糖-1,6-二磷酸——糖酵解的限速步骤。被AMP、果糖-2,6-二磷酸激活。被ATP、柠檬酸抑制。",
     "PFK-1: paso limitante de glucolisis. Activa: AMP, fructosa-2,6-bifosfato. Inhibe: ATP, citrato."),
    ("In gluconeogenesis, which enzyme bypasses the irreversible pyruvate kinase step of glycolysis?",
     ["PEP carboxykinase (PEPCK) + pyruvate carboxylase", "Fructose-1,6-bisphosphatase", "Glucose-6-phosphatase", "Phosphoglucomutase", "Aldolase B"], 0,
     "Pyruvate carboxylase (pyruvate → OAA) + PEPCK (OAA → PEP) bypass pyruvate kinase. Other bypasses: fructose-1,6-bisphosphatase bypasses PFK-1, glucose-6-phosphatase bypasses hexokinase/glucokinase.",
     "丙酮酸羧化酶（丙酮酸→草酰乙酸）+ PEPCK（草酰乙酸→PEP）绕过丙酮酸激酶。其他绕过步骤：果糖-1,6-二磷酸酶绕过PFK-1，葡萄糖-6-磷酸酶绕过己糖激酶。",
     "Piruvato carboxilasa + PEPCK evitan piruvato quinasa. Fructosa-1,6-bifosfatasa evita PFK-1. Glucosa-6-fosfatasa evita hexoquinasa."),
    ("Which vitamin is required for carboxylation reactions (e.g., pyruvate carboxylase, acetyl-CoA carboxylase)?",
     ["Biotin (Vitamin B7)", "Thiamine (B1)", "Riboflavin (B2)", "Pantothenic acid (B5)", "Cobalamin (B12)"], 0,
     "Biotin is the cofactor for carboxylase enzymes: pyruvate carboxylase (gluconeogenesis), acetyl-CoA carboxylase (fatty acid synthesis), propionyl-CoA carboxylase, 3-methylcrotonyl-CoA carboxylase. Avidin in raw egg whites binds biotin → deficiency.",
     "生物素是羧化酶的辅因子：丙酮酸羧化酶、乙酰辅酶A羧化酶等。生蛋清中的亲和素结合生物素→缺乏。",
     "Biotina: cofactor de carboxilasas. Avidina en clara de huevo cruda se une a biotina → deficiencia."),
    ("Which lipoprotein is responsible for reverse cholesterol transport?",
     ["HDL", "LDL", "VLDL", "IDL", "Chylomicrons"], 0,
     "HDL mediates reverse cholesterol transport: picks up excess cholesterol from peripheral tissues and returns it to the liver. HDL is 'good cholesterol.' LDL delivers cholesterol to tissues ('bad cholesterol'). VLDL carries endogenous TGs.",
     "HDL介导胆固醇逆向转运：从外周组织收集多余胆固醇返回肝脏。HDL是"好胆固醇"。LDL将胆固醇运送到组织。VLDL携带内源性甘油三酯。",
     "HDL: transporte reverso de colesterol (recoge exceso de tejidos → higado). Colesterol 'bueno'. LDL: entrega colesterol a tejidos."),
    ("What is the product of the committed step of fatty acid synthesis?",
     ["Malonyl-CoA (via acetyl-CoA carboxylase)", "Acetyl-CoA", "Citrate", "Palmitate", "HMG-CoA"], 0,
     "Acetyl-CoA carboxylase converts acetyl-CoA → malonyl-CoA (committed step, requires biotin, activated by citrate, inhibited by palmitoyl-CoA). Fatty acid synthase then elongates malonyl-CoA + acetyl-CoA → palmitate (C16).",
     "乙酰辅酶A羧化酶将乙酰辅酶A→丙二酰辅酶A（关键步骤，需生物素），然后脂肪酸合酶延伸生成棕榈酸酯（C16）。",
     "Acetil-CoA carboxilasa: acetil-CoA → malonil-CoA (paso comprometido, requiere biotina). Acido graso sintasa elonga → palmitato (C16)."),
    ("A patient has homocystinuria. Which vitamin can be used to treat the CBS deficiency form?",
     ["Pyridoxine (Vitamin B6)", "Cobalamin (B12)", "Folate (B9)", "Thiamine (B1)", "Ascorbic acid (C)"], 0,
     "Classic homocystinuria = cystathionine beta-synthase (CBS) deficiency. B6 (pyridoxine) is a cofactor for CBS — some patients are B6-responsive. Features: marfanoid habitus, lens dislocation (downward), intellectual disability, thromboembolism.",
     "经典同型胱氨酸尿症 = 胱硫醚β合酶缺乏。B6是CBS辅因子。特征：马凡样体型、晶状体脱位（向下）、智力障碍、血栓栓塞。",
     "Homocistinuria clasica: deficiencia CBS. B6 cofactor de CBS. Rasgos: habitus marfanoide, luxacion cristalino (abajo), discapacidad intelectual, tromboembolismo."),
    ("Which enzyme deficiency causes von Gierke disease (glycogen storage disease type I)?",
     ["Glucose-6-phosphatase", "Glycogen phosphorylase (muscle)", "Debranching enzyme", "Acid maltase (alpha-glucosidase)", "Branching enzyme"], 0,
     "Von Gierke disease (GSD I): glucose-6-phosphatase deficiency → cannot release free glucose from liver → severe fasting hypoglycemia, hepatomegaly, lactic acidosis, hyperuricemia, hypertriglyceridemia.",
     "Von Gierke病：葡萄糖-6-磷酸酶缺乏→不能从肝脏释放游离葡萄糖→严重空腹低血糖、肝大、乳酸酸中毒、高尿酸血症、高甘油三酯血症。",
     "Enfermedad von Gierke: deficiencia glucosa-6-fosfatasa → hipoglucemia severa en ayuno, hepatomegalia, acidosis lactica, hiperuricemia."),
    ("What are the 4 fat-soluble vitamins?",
     ["A, D, E, K", "B1, B2, B3, B5", "B6, B9, B12, C", "C, D, E, K", "A, B, C, D"], 0,
     "Fat-soluble vitamins: A (retinol, vision), D (calcium homeostasis), E (antioxidant, neurologic), K (coagulation factors II, VII, IX, X). Malabsorption syndromes (CF, biliary obstruction, pancreatic insufficiency) cause deficiencies.",
     "脂溶性维生素：A（视觉）、D（钙稳态）、E（抗氧化、神经）、K（凝血因子）。吸收不良综合征可引起缺乏。",
     "Vitaminas liposolubles: A (vision), D (homeostasis calcio), E (antioxidante), K (coagulacion). Deficiencias en sindromes malabsortivos."),
    ("Which compound is the primary donor of methyl groups in the body?",
     ["S-adenosylmethionine (SAM)", "Tetrahydrofolate (THF)", "Methylcobalamin", "Choline", "Betaine"], 0,
     "SAM is the universal methyl group donor for DNA methylation, neurotransmitter synthesis (NE→E), creatine synthesis, etc. Derived from methionine + ATP. After donation, becomes S-adenosylhomocysteine (SAH), then homocysteine.",
     "SAM是体内主要的甲基供体，用于DNA甲基化、神经递质合成等。由蛋氨酸+ATP生成。供甲基后变为SAH，再变为同型半胱氨酸。",
     "SAM: principal donante de grupos metilo. Sintesis de creatina, metilacion ADN, etc. Derivado de metionina + ATP."),
    ("In the urea cycle, which amino acid directly donates one of the two nitrogen atoms of urea?",
     ["Aspartate", "Glycine", "Alanine", "Glutamine", "Serine"], 0,
     "Urea contains 2 nitrogens: one from free ammonia (NH3), one from aspartate. Ornithine transcarbamylase deficiency (X-linked) is the most common urea cycle disorder. Carbamoyl phosphate synthetase I requires N-acetylglutamate.",
     "尿素含两个氮原子：一个来自游离氨，一个来自天冬氨酸。鸟氨酸转氨甲酰酶缺乏症（X连锁）是最常见的尿素循环障碍。",
     "Urea contiene 2 N: uno de amonio libre, uno de aspartato. Deficit OTC (ligado X) es el mas comun."),
    ("What type of bond links amino acids in a protein?",
     ["Peptide bond (amide bond)", "Glycosidic bond", "Phosphodiester bond", "Hydrogen bond", "Disulfide bond"], 0,
     "Peptide bond = covalent amide bond between alpha-carboxyl of one amino acid and alpha-amino of another. Has partial double-bond character → planar, rigid, trans configuration. Broken by proteases and strong acid/base hydrolysis.",
     "肽键 = 一个氨基酸α羧基与另一个氨基酸α氨基之间的共价酰胺键。具有部分双键特征→平面、刚性、反式构型。",
     "Enlace peptidico: enlace amida covalente entre carboxilo alfa de un aa y amino alfa de otro. Caracter de doble enlace parcial."),
    ("Which organ is the primary site of ketone body synthesis?",
     ["Liver (mitochondria)", "Kidney", "Brain", "Muscle", "Adipose tissue"], 0,
     "Ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone) are synthesized in liver mitochondria from acetyl-CoA during prolonged fasting/starvation. The liver cannot use ketone bodies (lacks CoA transferase). Brain and muscle use them as fuel.",
     "酮体在肝线粒体由乙酰辅酶A合成，见于长时间禁食/饥饿。肝脏不能利用酮体。脑和肌肉将酮体作为燃料。",
     "Cuerpos cetonicos sintetizados en mitocondrias hepaticas durante ayuno. Higado no puede usarlos. Cerebro y musculo los usan como combustible."),
    ("In oxidative phosphorylation, which complex is the primary entry point for electrons from NADH?",
     ["Complex I (NADH dehydrogenase)", "Complex II (succinate dehydrogenase)", "Complex III (cytochrome bc1)", "Complex IV (cytochrome c oxidase)", "ATP synthase (Complex V)"], 0,
     "NADH → Complex I → CoQ → Complex III → Cyt c → Complex IV → O2. FADH2 → Complex II → CoQ → rest of chain. Complex I and II both feed electrons to CoQ. NADH produces ~2.5 ATP; FADH2 produces ~1.5 ATP.",
     "NADH→复合体I→CoQ→复合体III→细胞色素c→复合体IV→O2。FADH2→复合体II→CoQ。NADH产生约2.5 ATP，FADH2产生约1.5 ATP。",
     "NADH → Complejo I → CoQ → III → Cit c → IV → O2. FADH2 → Complejo II → CoQ. NADH ~2.5 ATP, FADH2 ~1.5 ATP."),
    ("Which enzyme deficiency leads to galactosemia?",
     ["Galactose-1-phosphate uridylyltransferase (GALT)", "Galactokinase", "UDP-galactose epimerase", "Aldose reductase", "Lactase"], 0,
     "Classic galactosemia = GALT deficiency → galactose-1-phosphate accumulation → liver damage, cataracts, intellectual disability, E. coli sepsis in neonates. Treatment: galactose-free diet. Newborn screening detects this.",
     "经典半乳糖血症 = GALT缺乏→半乳糖-1-磷酸堆积→肝损伤、白内障、智力障碍、新生儿大肠杆菌败血症。治疗：无半乳糖饮食。",
     "Galactosemia clasica: deficit GALT → acumulacion galactosa-1-fosfato → dano hepatico, cataratas, sepsis E. coli neonatal."),
    ("What is the function of topoisomerase II in DNA replication?",
     ["Relieves positive supercoils ahead of the replication fork by making double-strand breaks", "Synthesizes RNA primers", "Unwinds the DNA double helix", "Seals Okazaki fragments", "Prevents strand reannealing"], 0,
     "Topoisomerase II (DNA gyrase in bacteria) cuts both strands, passes another segment through, reseals → relieves supercoils. Etoposide and fluoroquinolones inhibit topo II. Topoisomerase I cuts single strand.",
     "拓扑异构酶II切断双链，通过另一段DNA，重新连接→解除超螺旋。依托泊苷和氟喹诺酮类抑制topo II。拓扑异构酶I切断单链。",
     "Topoisomerasa II: corta ambas hebras, pasa segmento, resella → alivia superenrollamiento. Etoposido y fluoroquinolonas inhiben topo II."),
]

for q in biochem_qs_step1:
    q(next_id, 'step1', 'Biochemistry', *q); next_id += 1

# --- Microbiology (15 questions) ---
micro_qs_step1 = [
    ("Which bacterium is the most common cause of uncomplicated urinary tract infections?",
     ["Escherichia coli (UPEC strains)", "Klebsiella pneumoniae", "Proteus mirabilis", "Enterococcus faecalis", "Staphylococcus saprophyticus"], 0,
     "E. coli (UPEC) accounts for 75-95% of uncomplicated UTIs. Virulence factors: type 1 pili, P pili (adhesion), hemolysin. Other causes: Staphylococcus saprophyticus (young women), Proteus (calculi), Klebsiella.",
     "大肠杆菌（UPEC）占75-95%非复杂性UTI。毒力因子：1型菌毛、P菌毛（黏附）、溶血素。其他病原体：腐生葡萄球菌（年轻女性）、变形杆菌（结石）、克雷伯杆菌。",
     "E. coli UPEC: 75-95% ITU no complicadas. Factores: pili tipo 1, pili P, hemolisina. S. saprophyticus en mujeres jovenes."),
    ("Which infectious disease is prevented by the MMR vaccine, and what type of vaccine is it?",
     ["Measles, Mumps, Rubella — live attenuated vaccine", "Measles, Meningitis, Rabies — killed vaccine", "Measles, Mumps, Rotavirus — subunit vaccine", "Measles, Meningitis, RSV — conjugate vaccine", "Measles, Malaria, Rubella — toxoid vaccine"], 0,
     "MMR = live attenuated vaccine for Measles, Mumps, Rubella. Contraindicated in pregnancy and immunocompromised. Given at 12-15 months and 4-6 years. Associated with febrile seizures (not autism — this link is disproven).",
     "MMR = 麻疹、腮腺炎、风疹活减毒疫苗。妊娠期和免疫功能低下者禁用。12-15月龄和4-6岁接种。",
     "Triple virica: vacuna viva atenuada para sarampion, paperas, rubeola. Contraindicada embarazo e inmunocomprometidos."),
    ("A patient with HIV has a CD4 count of 45 cells/uL and presents with multiple ring-enhancing brain lesions on MRI. What is the most likely cause?",
     ["Toxoplasma gondii", "Cryptococcus neoformans", "Cytomegalovirus", "Progressive multifocal leukoencephalopathy (JC virus)", "Primary CNS lymphoma"], 0,
     "Toxoplasmosis (CD4 <100): multiple ring-enhancing lesions on MRI. Treatment: pyrimethamine + sulfadiazine + leucovorin. Cryptococcus: CD4 <50, meningitis. CMV retinitis: CD4 <50. PML: non-enhancing lesions, CD4 <100.",
     "弓形虫病（CD4<100）：MRI多发环形强化病灶。治疗：乙胺嘧啶+磺胺嘧啶+亚叶酸。隐球菌：CD4<50，脑膜炎。",
     "Toxoplasmosis (CD4 <100): lesiones anulares con realce en MRI. Tratamiento: pirimetamina + sulfadiazina + leucovorina."),
    ("Which medium is used to culture Neisseria gonorrhoeae?",
     ["Thayer-Martin agar (chocolate agar with antibiotics)", "Blood agar", "MacConkey agar", "Lowenstein-Jensen medium", "Sabouraud agar"], 0,
     "N. gonorrhoeae requires Thayer-Martin (modified chocolate agar with vancomycin, colistin, nystatin to suppress normal flora). Gram-negative diplococci. Oxidase positive. First-line treatment: ceftriaxone + doxycycline (for possible chlamydia co-infection).",
     "淋球菌需Thayer-Martin培养基培养。革兰阴性双球菌。氧化酶阳性。一线治疗：头孢曲松+多西环素（覆盖可能合并的衣原体感染）。",
     "N. gonorrhoeae: medios Thayer-Martin. Diplococos gram negativos. Oxidasa positivo. Tratamiento: ceftriaxona + doxiciclina."),
    ("Which virus causes infectious mononucleosis, and which cell type does it infect?",
     ["Epstein-Barr virus (EBV) — infects B lymphocytes via CD21", "Cytomegalovirus — infects T lymphocytes", "HIV — infects macrophages", "Adenovirus — infects respiratory epithelium", "Parvovirus B19 — infects erythroid precursors"], 0,
     "EBV (HHV-4) infects B cells via CD21 receptor → atypical lymphocytosis (CD8+ T cells reacting to infected B cells). Monospot test detects heterophile antibodies. Associated with Burkitt lymphoma, nasopharyngeal carcinoma, Hodgkin lymphoma.",
     "EBV通过CD21受体感染B细胞→非典型淋巴细胞增多。Monospot试验检测嗜异性抗体。与伯基特淋巴瘤、鼻咽癌、霍奇金淋巴瘤相关。",
     "VEB infecta linfocitos B via CD21 → linfocitosis atipica. Prueba Monospot detecta anticuerpos heterofilos. Asociado linfoma Burkitt, carcinoma nasofaringeo."),
    ("What is the most common cause of bacterial meningitis in neonates (0-3 months)?",
     ["Group B Streptococcus (S. agalactiae) and E. coli", "Neisseria meningitidis", "Streptococcus pneumoniae", "Haemophilus influenzae type b", "Listeria monocytogenes"], 0,
     "GBS and E. coli are top causes of neonatal meningitis. Listeria also important in neonates. In children/adults: S. pneumoniae, N. meningitidis. Elderly: S. pneumoniae, Listeria. Empiric treatment: ampicillin + cefotaxime (or amp + gentamicin).",
     "GBS和大肠杆菌是新生儿脑膜炎最常见病原体。儿童/成人：肺炎链球菌、脑膜炎奈瑟菌。老年人：肺炎链球菌、李斯特菌。经验治疗：氨苄西林+头孢噻肟。",
     "Meningitis neonatal: SGB y E. coli. Ninos/adultos: S. pneumoniae, N. meningitidis. Tratamiento empirico: ampicilina + cefotaxima."),
    ("Which fungal infection is associated with pigeon droppings and causes meningitis in immunocompromised patients?",
     ["Cryptococcus neoformans", "Histoplasma capsulatum", "Coccidioides immitis", "Aspergillus fumigatus", "Candida albicans"], 0,
     "Cryptococcus neoformans: encapsulated yeast found in pigeon droppings. India ink stain shows capsule. Latex agglutination detects capsular antigen in CSF. Treatment: amphotericin B + flucytosine, then fluconazole maintenance in HIV patients.",
     "新型隐球菌：荚膜酵母菌，存在于鸽粪中。印度墨汁染色显示荚膜。CSF乳胶凝集试验检测荚膜抗原。治疗：两性霉素B+氟胞嘧啶，HIV患者随后氟康唑维持。",
     "Cryptococcus neoformans: levadura encapsulada en heces palomas. Tinta china muestra capsula. Tratamiento: anfotericina B + flucitosina, luego fluconazol."),
    ("What is the mechanism of action of acyclovir?",
     ["Guanosine analog — requires viral thymidine kinase for activation, inhibits viral DNA polymerase", "Inhibits viral neuraminidase", "Blocks viral uncoating", "Inhibits viral protease", "Inhibits viral integrase"], 0,
     "Acyclovir: guanosine analog → phosphorylated by viral thymidine kinase (HSV/VZV) → triphosphate form inhibits viral DNA polymerase and causes chain termination. Most effective against HSV-1, HSV-2, VZV. Less active against EBV, CMV.",
     "阿昔洛韦：鸟苷类似物→由病毒胸苷激酶磷酸化→三磷酸形式抑制病毒DNA聚合酶并引起链终止。对HSV-1/2和VZV最有效。",
     "Aciclovir: analogo guanosina → fosforilado por timidina quinasa viral → inhibe ADN polimerasa viral. Mas efectivo contra VHS-1/2, VVZ."),
    ("Which parasite causes 'foot swelling' (elephantiasis) and is transmitted by mosquitoes?",
     ["Wuchereria bancrofti (lymphatic filariasis)", "Onchocerca volvulus", "Loa loa", "Schistosoma haematobium", "Dracunculus medinensis"], 0,
     "Wuchereria bancrofti causes lymphatic filariasis → adult worms block lymphatics → lymphedema, elephantiasis. Transmitted by mosquitoes (Culex, Anopheles, Aedes). Treatment: diethylcarbamazine (DEC) or ivermectin + albendazole.",
     "班氏丝虫引起淋巴丝虫病→成虫堵塞淋巴管→淋巴水肿、象皮肿。由蚊子传播。治疗：乙胺嗪或伊维菌素+阿苯达唑。",
     "Wuchereria bancrofti: filariasis linfatica → obstruccion linfatica → elefantiasis. Transmitida por mosquitos. Tratamiento: dietilcarbamazina o ivermectina + albendazol."),
    ("Which pathogen is detected by the urease breath test?",
     ["Helicobacter pylori", "Mycobacterium tuberculosis", "Clostridium difficile", "Candida albicans", "Giardia lamblia"], 0,
     "H. pylori produces urease → converts urea to ammonia + CO2. Urea breath test: patient ingests 13C/14C-labeled urea → if H. pylori present, labeled CO2 detected in breath. Also detected by rapid urease test on biopsy, stool antigen test.",
     "幽门螺杆菌产生尿素酶。尿素呼气试验：患者摄入标记尿素→如存在Hp，呼气中检测到标记CO2。也可通过快速尿素酶试验和粪便抗原检测。",
     "H. pylori produce ureasa. Prueba aliento: ingiere urea marcada → si Hp presente, CO2 marcado en aliento. Tambien test rapido ureasa, antigeno en heces."),
    ("A 2M child presents with severe, watery diarrhea and vomiting. Stool studies show non-bloody diarrhea with fecal leukocytes absent. Which virus is the most common cause?",
     ["Rotavirus", "Norovirus", "Adenovirus", "Astrovirus", "Sapovirus"], 0,
     "Rotavirus is the most common cause of severe diarrhea in children <5 years. Non-bloody, watery diarrhea + vomiting + fever. Fecal leukocytes typically absent. Vaccine: live oral rotavirus vaccine (RotaTeq, Rotarix) at 2, 4, 6 months.",
     "轮状病毒是5岁以下儿童严重腹泻的最常见原因。非血性水样腹泻+呕吐+发热。粪白细胞通常阴性。疫苗：口服活轮状病毒疫苗（五价/单价），2、4、6月龄接种。",
     "Rotavirus: causa mas comun de diarrea severa en <5 anos. Acuosa, no sanguinolenta + vomitos. Vacuna oral viva atenuada a 2, 4, 6 meses."),
    ("A 35M HIV patient develops retinitis with 'ketchup and mayonnaise' appearance on fundoscopy. What is the cause?",
     ["Cytomegalovirus (CMV)", "Toxoplasma gondii", "Herpes simplex virus", "Varicella-zoster virus", "Candida albicans"], 0,
     "CMV retinitis: CD4 <50, hemorrhagic retinitis with perivascular exudates (pizza pie/ketchup and mayonnaise). Can cause blindness. Treatment: valganciclovir, ganciclovir. Initiate ART for immune recovery.",
     "CMV视网膜炎：CD4<50，出血性视网膜炎伴血管周围渗出。可致盲。治疗：缬更昔洛韦、更昔洛韦。启动ART恢复免疫功能。",
     "Retinitis CMV: CD4 <50, aspecto pizza/ketchup-mayonesa. Tratamiento: valganciclovir, ganciclovir. Iniciar TAR."),
    ("What is the Gram stain and morphology of Vibrio cholerae?",
     ["Gram-negative, comma-shaped (curved) rod", "Gram-positive cocci in chains", "Gram-negative diplococci", "Gram-positive spore-forming rod", "Gram-negative coccobacillus"], 0,
     "V. cholerae: gram-negative comma-shaped rod, oxidase positive, grows in alkaline media. Produces cholera toxin (ADP-ribosylates Gs protein → increased cAMP → massive watery diarrhea, 'rice-water stools'). Treatment: aggressive rehydration + doxycycline.",
     "霍乱弧菌：革兰阴性逗点状杆菌，氧化酶阳性。产生霍乱毒素→米泔水样大便。治疗：积极补液+多西环素。",
     "V. cholerae: baston curvo gram negativo, oxidasa positivo. Toxina colerica → diarrea acuosa masiva. Tratamiento: rehidratacion agresiva + doxiciclina."),
    ("Which bacterial virulence factor allows Streptococcus pneumoniae to evade phagocytosis?",
     ["Polysaccharide capsule", "M protein", "Protein A", "IgA protease", "Coagulase"], 0,
     "S. pneumoniae capsule is the major virulence factor → prevents phagocytosis. Antibodies against capsule are protective (basis of pneumococcal vaccines PCV13, PPSV23). M protein = S. pyogenes. Protein A = S. aureus. IgA protease = N. gonorrhoeae, H. influenzae.",
     "肺炎链球菌荚膜是主要毒力因子→阻止吞噬作用。抗荚膜抗体有保护作用（肺炎球菌疫苗的基础）。",
     "Capsula polisacarida de S. pneumoniae: principal factor virulencia → evita fagocitosis. Base de vacunas PCV13, PPSV23."),
    ("A 25F has painless genital ulcer with indurated borders and bilateral inguinal lymphadenopathy. Darkfield microscopy shows spirochetes. What is the diagnosis?",
     ["Primary syphilis (Treponema pallidum)", "Herpes simplex virus", "Chancroid (Haemophilus ducreyi)", "Lymphogranuloma venereum", "Granuloma inguinale"], 0,
     "Primary syphilis: painless chancre (indurated, clean base) + painless lymphadenopathy. Diagnosed by darkfield microscopy or serology (RPR/VDRL screening, FTA-ABS confirmatory). Treatment: penicillin G benzathine IM (single dose).",
     "一期梅毒：无痛硬下疳（硬结，基底清洁）+无痛淋巴结肿大。暗视野显微镜检查或血清学确诊。治疗：苄星青霉素G肌注。",
     "Sifilis primaria: chancro indoloro + linfadenopatia indolora. Microscopia campo oscuro, serologia. Tratamiento: penicilina G benzatinica IM."),
]

for q in micro_qs_step1:
    q(next_id, 'step1', 'Microbiology', *q); next_id += 1

print(f"Generated {len(questions)} questions (IDs {START_ID}-{next_id-1})")
print(questions[-1]['id'])
sys.stdout.write(to_ts())
